### ISSUE TITLE
Create dist only bower

### ISSUE THREAD

**Issue by david2tm** [benmarch/angular-ui-tour#10]
Hello,

Can you create a new bower package with only dist folder? Having sources in production is not really needed, and whoever needs sources to work on them, should just git clone `em anyway.

http://bob.yexley.net/creating-and-maintaining-your-own-bower-package/

Thanks

**Comment by benmarch** [comment]
Hey @david2tm, I will add everything but dist/ to the Bower ignores. I use the separate repo pattern at work, but I prefer just to use grunt release for my open source projects.
