### ISSUE TITLE
Question re: integration with custom router

### ISSUE THREAD

**Issue by FlowerFountain** [benmarch/angular-ui-tour#100]
**I am using the _exact_ versions of the following libraries:**

* AngularJS: 1.5.9
* Angular Bootstrap: 2.3.0
* Angular UI Tour: 0.6.4

**I have installed this library via:** downloaded

I'm trying to integrate `angular-ui-tour` into a little project of mine and I'm
running into a minor issue regarding routing.

It's a very simple Angular 1.5 app. It basically loads some data from Firebase,
and uses simple forms to edit this data. These forms are spread out over
different pages. Those different pages are generated and managed in
BootstrapStudio (a WYSIWYG editor). All pages use the same `MainCtrl`, since
there is very little actual logic.

To facilitate a make-shift single page application, I've hacked together a
simple router. It hijacks `<a>` tags and loads the linked content into the body,
replacing the current template, afterwards updating the window location using 
`history.pushState`.

---

It all works fine and dandy, until I throw `angular-ui-tour` into the mix. My
`history.pushState` call barely has the chance to update URL before it's
reset to previous value, effectively breaking refresh and search parameters. 

I understand `angular-ui-tour` was developed to cooperate with `ngRoute` and
`ui.router`, so I suspect it has a listener somewhere that is incompatible with
my excuse for a router.

Since you know your codebase a lot better than myself, could you perhaps point me
towards said listener?

---

Demo here:

https://run.plnkr.co/plunks/5prnv1LAAISd88VTUrEu/

You can navigate between the two pages. The HTML is updated, but the URL quickly
flashes back to where you came from.

**Comment by FlowerFountain** [comment]
Found it!

It wasn't code from `angular-ui-tour`, but rather its dependency on `$location`
service. It places a watch on the window location and was counteracting
my url changes. The `$location` service was able to play nice with my 
router when setting `html5Mode(true)`, since then we're both parsing the
url in the same way.

Thanks for making this library :)

**Comment by benmarch** [comment]
Hey @FlowerFountain, sorry I didn't respond earlier, I was at the AWS re:Invent conference all last week. I'm glad you were able to resolve the issue.

Cheers,
Ben
