### ISSUE TITLE
Step for a manual install

### ISSUE THREAD

**Issue by mattifh** [benmarch/angular-ui-tour#101]
@benmarch could you please provide some steps for a manual install (not through any code repository management). I have downloaded the version 0.5.5, installed it and added the dependency to my directive. However, I am unable to get the tour started and I am receiving the following error messages:

Error: [$injector:unpr] Unknown provider: TourConfigProviderProvider <- TourConfigProvider

TypeError: CustomEvent.fireAll is not a function

**Comment by benmarch** [comment]
Everything about installing the library is available in the README. No additional steps are required other than that you will have to manually download the dependencies. Please provide additional information about the error (full stack trace would be helpful) and the versions of all related libraries.

**Comment by benmarch** [comment]
Removed the custom event implementation in the next release which will resolve this issue.

**Comment by benmarch** [comment]
Version 0.8.0 has been released, please verify that this issue has been resolved. Note that there are a few breaking changes that might need to be addressed: https://github.com/benmarch/angular-ui-tour#versions.
