### ISSUE TITLE
[404] angular-ui-tour.min.js

### ISSUE THREAD

**Issue by jeff-li** [benmarch/angular-ui-tour#103]
angular-ui-tour.min.js has been removed?

https://cdn.rawgit.com/benmarch/angular-ui-tour/master/dist/angular-ui-tour.min.js Failed to load resource: the server responded with a status of 404 ()

**Comment by benmarch** [comment]
Yes, please don't use the master branch, use a specific version if you are going to use it as a CDN: https://cdn.rawgit.com/benmarch/angular-ui-tour/0.6.4/dist/angular-ui-tour.min.js
