### ISSUE TITLE
Angular UI Tour onBackdropClick callback in controller

### ISSUE THREAD

**Issue by iamdeadman** [benmarch/angular-ui-tour#106]
**I am using the _exact_ versions of the following libraries:**

* AngularJS: 1.4.x
* Angular Bootstrap: 0.14.3
* Angular UI Tour: 0.7.0

**I have installed this library via:** (NPM, Bower, or downloaded package) -- Bower

**I have observed the following behavior:**
http://stackoverflow.com/questions/41658115/angular-ui-tour-end-tour-on-backdrop-click

I am trying to end the tour on backdrop click like this in my controller template - 
```
<div class="grey-200 bg-big" ng-controller="SeriesController" ui-tour="myTour" ui-tour-backdrop="true"
     ui-tour-use-hotkeys="true" ui-tour-append-to-body="true" ui-tour-onBackdropClick="end_tour">

```

where `end_tour` is a function in my SeriesController. Might be I am using incorrect syntax or something but I have also tried - `end_tour()` instead of `end_tour` and it didn't work.

Any suggestions as to how this works ?

Thank and Regards,
Harshit Laddha

**Comment by benmarch** [comment]
Hey Harshit,

The syntax would be `ui-tour-on-backdrop-click="end_tour()"`.

-Ben

**Comment by iamdeadman** [comment]
Thanks for the quick reply. I forgot about the camel casing. Also, I am trying to highlight step elements by adding 
`tour-step-backdrop="true"`

to the tour steps and 

`ui-tour="myTour" ui-tour-backdrop-z-index="100" ui-tour-backdrop="true"  ui-tour-append-to-body="true"`

to the container, but still the backdrop has a z-index of 10000. and only when I increase the z-index of the element to be highlighted to > 10000, it becomes visible. 

How do I properly assign a z-index and add highlight options to individual tour steps.

Thanks and Regards,
Harshit Laddha

**Comment by benmarch** [comment]
Hey Harshit,

Your syntax looks correct, but I'm not sure why your target isn't visible. The zIndex actually shouldn't matter since it doesn't cover the target, it just creates a window around it. What are the computed dimensions of your target? It sounds like it might be 0, 0. I'll look into why the zIndex isn't set properly.

-Ben

**Comment by iamdeadman** [comment]
Hi Ben,

I tried with the following tour steps again - 
```

<md-button tour-step="step1" tour-step-enabled="true" tour-step-backdrop="true" tour-step-title="Register Now" tour-step-content="Register for Test Series by clicking on the button below."
                       class="md-raised md-primary" ng-show="!hasAccess" ng-click="series_register()">Register Now</md-button>
            <md-button tour-step="step2" tour-step-enabled="true" tour-step-backdrop="true" tour-step-title="Invite friends" tour-step-content="Invite your friends by email for this Test Series by clicking here"
                    class="md-raised" ng-click="invite_friends()" ng-show="isLoggedIn">Invite Friends</md-button>
```

and I am attaching the screenshots of the issue I am facing now 

![tour3](https://cloud.githubusercontent.com/assets/3391877/21982372/fef77e5a-dc11-11e6-939e-2e417e18223e.png)
![tour2](https://cloud.githubusercontent.com/assets/3391877/21982373/fefcfba0-dc11-11e6-8201-8bd20256157a.png)
![tooltip1](https://cloud.githubusercontent.com/assets/3391877/21982374/ff02b478-dc11-11e6-996a-afed3c08eff8.png)


my container code looks like - 

```
<div class="grey-200 bg-big" ng-controller="SeriesController" ui-tour="myTour" ui-tour-backdrop-z-index="100" ui-tour-placement="bottom"
     ui-tour-use-hotkeys="true" ui-tour-backdrop="true"  ui-tour-append-to-body="true">

```

and as you can see only for the first time when the page is loading it is highlighting the wrong element but when I am navigating to it back after going to the second step first it highlights the correct element.

I have not added any extra css other than this - 

```
.tour-backdrop {
  background-color: rgba(0, 0, 0, 0.5);
}
```

**Comment by iamdeadman** [comment]
Also I notice that in certain cases, some part of the popovers goes off the screen due to incorrect offset calculations like this one - 

![image](https://cloud.githubusercontent.com/assets/3391877/22007916/ac24c148-dc9c-11e6-8fb9-4fc93060e00e.png)

So, how can I make sure that the left or any of the offsets does not go less than 0. For example - in case of the above screen -


![error4](https://cloud.githubusercontent.com/assets/3391877/22008134/48c88de4-dc9e-11e6-9c5f-cff59496211c.png)


the left offset is -389px, 
can it be changed dynamically and responsively to not go below 0px and change the popover arrowheads position accordingly

**Comment by benmarch** [comment]
Hi Harshit, 

I noticed the miscalculation locally, and it is my highest priority for the next release.

As far as the popover falling off the page, I am working on a better general positioning solution that should fix it, but you are better off using placement=top for that one.

Thanks,
Ben

**Comment by iamdeadman** [comment]
Okay, thanks for the update. Ben. If you need any help from me for the next release, I would be happy to help.
