### ISSUE TITLE
Scrolling elements instead of body

### ISSUE THREAD

**Issue by kwieckowski-neducatio** [benmarch/angular-ui-tour#110]
**I am using the _exact_ versions of the following libraries:**

Demo page

**I have observed the following behavior:**

When the following code is added to .main-content element
```css
.main-content {
  height: 300px;
  overflow: auto;
}
```

and the tour is started, the tour breaks after a few steps due to body element is being scrolled instead of an element containing the tour-step. 

**This is how I expected it to behave:**

It's kinda annoying on full browser height pages. The tour should try to scroll the element that contains the tour-step if it's overflowing. Body element should be scrolled only after no other parent element is scrollable.

**Comment by benmarch** [comment]
I'll take a look at this, my changes for 0.8.0 might inadvertently fix this.

**Comment by benmarch** [comment]
I set this up so that it will scroll the scroll parent, but right now it will not scroll the scroll parent into view (which i think fits your use case). I can enhance it later if desired.

**Comment by benmarch** [comment]
Version 0.8.0 has been released, please verify that this issue has been resolved. Note that there are a few breaking changes that might need to be addressed: https://github.com/benmarch/angular-ui-tour#versions.
