### ISSUE TITLE
remove a Comment that course an error

### ISSUE THREAD

**Issue by Weestdudochnicht** [benmarch/angular-ui-tour#112]
can you please remove that line : //# sourceMappingURL=angular-ui-tour.js.map from the angular-ui-tour.js
becouse it throws always an error

**Comment by willsteinmetz** [comment]
👍

**Comment by benmarch** [comment]
Version 0.8.0 has been released, please verify that this issue has been resolved. Note that there are a few breaking changes that might need to be addressed: https://github.com/benmarch/angular-ui-tour#versions.
