### ISSUE TITLE
Angular UI Tour Demo Repo

### ISSUE THREAD

**Issue by Mr-Anonymous** [benmarch/angular-ui-tour#115]
hi,

Thank you for this awesome Angular Ui Tour Plugin.

I am looking for the demo codes and I cant locate it. Do you have a Demo Tree Repo? I tried this url after finding it in one of your old issues here but its coming up as 404:
```
https://github.com/benmarch/angular-ui-tour/tree/master/demo
```
I need to look at the demo samples so I can implement similar tour in my app. It will help me get started. Can someone tell me where I can find the source files for the demo page please?

Thanks,
Neel.

**Comment by benmarch** [comment]
Hey Neel, here is the (mostly) up-to-date demo: http://benmarch.github.io/angular-ui-tour/#/docs
