### ISSUE TITLE
Switching Between Bootstrap Tabs in Angular UI Tour

### ISSUE THREAD

**Issue by Mr-Anonymous** [benmarch/angular-ui-tour#117]
**I am using the _exact_ versions of the following libraries:**

* AngularJS: 1.5.9
* Angular Bootstrap: 2.4.0
* Angular UI Tour: 0.7.0

How can I use the Angular UI Tour between tabs? For example, I have tabs like below. I want the tour to start from Tab 1, and after finishing the steps in Tab 1, I want it to go to Tab 2, etc.. without the user needing to manually click the Tab 2. Is there a way to make Tab 2 active when user clicks the Next from the last step in Tab 1? I suspect I may need to use the `onNext()` event, but can someone give me an rough sample on how this is done or how the next Tab is made active in `onNext()` with Angular and Boostrap UI please?

```
<uib-tabset>
  <uib-tab>
   <uib-tab-heading>
      Tab 1
   </uib-tab-heading>
   <div class="panel-body">
       This is my content 1
   </div>
  </uib-tab>

  <uib-tab>
   <uib-tab-heading>
      Tab 2
   </uib-tab-heading>
   <div class="panel-body">
       This is my content 2
   </div>
  </uib-tab>

  <uib-tab>
   <uib-tab-heading>
      Tab 3
   </uib-tab-heading>
   <div class="panel-body">
       This is my content 3
   </div>
  </uib-tab>
</uib-tabset>
```

Thanks,
Neel.

**Comment by benmarch** [comment]
Hey Neel,

It's probably best to use `onShow()` to reveal the current step's tab. For example, if you go from tab 1 to tab 2, then on the step in tab 2 add something like `on-show="tab.show()"` (or however the Angular UI API does it).

`onShow()` is executed before the popup is displayed, so it should switch tabs and then display the popup properly. You _might_ need to run a digest after showing the tab to get the timing right, for now. I am (and have been) trying to fix all the timing issues with lifecycle hooks.

Thanks,
Ben

**Comment by Mr-Anonymous** [comment]
Thank you Ben. Your reply got me started and did it slightly different. This is how I have got it working at the moment:

I have the following in my controller to switch tabs:

```
function switchTab(tour, tab) {
       vm.currentTab = tab;
       return tour.resume();
 }
```

In the last step before the tab switch, I call the function like this:
```
tour-step-on-next="vm.switchTab(tour, 'tab-2')"
```

I added the tab source in html like this in the tour pages:
```
<li class="uib-tab nav-item" ng-class="{'active': vm.currentTab == 'tab-2'}">
</li>

<div class="tab-pane" ng-class="{'active': vm.currentTab == 'tab-2'}">
</div>
```

It seems to work and the tab changes during the tour.

Thank you for your help Ben. I appreciate that.

Thanks,
Neel.
