### ISSUE TITLE
Backdrop and ngSmoothScroll issues

### ISSUE THREAD

**Issue by Mr-Anonymous** [benmarch/angular-ui-tour#118]
**I am using the _exact_ versions of the following libraries:**

* AngularJS: 1.5.9
* Angular Bootstrap: 2.4.0
* Angular UI Tour: 0.7.0

I have created a big 50 steps multi-page tour in my Angular app now. Most of them are working well except a couple of behaviour that I find is annoying and breaks the ui.

1. Backdrop doesnt cover the whole page: During the tour, some of the pages have steps that uses backdrop. Sometimes, when I scroll down that page I notice that the backdrop doesnt cover the full height of that page. So I see the bright sections at the bottom since the backdrop stops incomplete. When I look at the inspect element, I see that the hight generated for the`tour-backdrop-bottom` doesnt cover till the bottom of the body height. Its seems to probably only covering the height of the viewport and not the height of the entire div. There are 2 instances here, if I disable the scrolling it sorta hides this, but I cant disable scrolling in all steps that uses backdrop. But even with scrolling disabled, if the tour step has to go to the bottom div and then the page scrolls to that location, then the section that is past the initial viewport doesnt have the backdrop which doesnt look good. So the backdrop is an issue here. I tried adding `min-height` css to `backdrop-bottom` like this but still this height issue happens in some pages:

```
.tour-backdrop-bottom {
	min-height: 100% !important;
}
```

2. `ngSmoothScroll` Issue: The `ngSmoothScroll` (version 2.0.0) is another issue that annoys me. In some pages where I have the tabs, the tour step starts at the top, goes down the page and then it goes up again. When the tour is going just down, its okay. However, when the next step has to go up to the top of the page again, then the `ngSmoothScroll` doesnt kick in straight away. It takes a bit of time to respond unless the user starts to move the cursor wondering what happened and then it scrolls to the top. This breaks the ui. After reading other issues here, I am using the non-minified version of `ngSmoothScroll` and this scrolling issue is there. Secondly, occasionally I also noticed that the smoothscroll doesnt scroll enough to the top and the element gets hidden behind the fixed top-navbar I have. I am not sure how to resolve these 2 issues since they are inconsistent. So basically, the `ngSmoothScroll` is a bit annoying and I wish there was another alternative for it even if it uses jquery to make it more smoother.

Tested it from Chrome.

Thanks for your help @benmarch

**Comment by Mr-Anonymous** [comment]
Okay, an update on this. The issue I have with the Backdrop height has to do due with the body css in my style that has `height: 100%;`. I had to add a class to the body when tour starts and then override the body css like this: 

```
body.tour {
   height: auto !important;
}
```
This seems to fix the height issue with backdrop.

I still have the scrolling issue when the step has to scroll to the top again.

**Comment by benmarch** [comment]
Hey Neel,

Sorry I didn't respond earlier. I have also experienced both of these issues, and they are top priority for version 0.8.0, which is coming along although I have little time to work on it. I'm hoping to release in the next couple weeks.

Thank you for your patience,
Ben

**Comment by Mr-Anonymous** [comment]
Thank you so much Ben. 

I really appreciate you for testing it and adding an update for this on 0.8.0. You are amazing and I am very happy to see active development in this. I know how tough it is with little time and I am much obliged for your assistance inspite of that.

Thank you kindly.

Cheers,
Neel.

**Comment by benmarch** [comment]
Using external backdrop library that _should_ fix the backdrop issue, and replace ngSmoothScroll with angular-scroll which definitely fixes the scrolling issues in the next release.

**Comment by benmarch** [comment]
Version 0.8.0 has been released, please verify that this issue has been resolved. Note that there are a few breaking changes that might need to be addressed: https://github.com/benmarch/angular-ui-tour#versions.
