### ISSUE TITLE
Failed to instantiate module bm.uiTour

### ISSUE THREAD

**Issue by yoannjauffroy** [benmarch/angular-ui-tour#119]
I am using the exact versions of the following libraries:

- AngularJS: 1.6.3
- Angular UI Bootstrap: 2.5.0
- Angular UI Tour: 0.7.0

I have installed this library via: **NPM**

I have this error in the console
```js
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module app.core due to:
Error: [$injector:modulerr] Failed to instantiate module bm.uiTour due to:
Error: [$injector:unpr] Unknown provider: $uibTooltipProvider
http://errors.angularjs.org/1.6.3/$injector/unpr?p0=%24uibTooltipProvider
```

and my import file

```js
require('angular');
require('angular-sanitize');
require('angular-ui-bootstrap/dist/ui-bootstrap-tpls.js');
require('ngSmoothScroll/dist/angular-smooth-scroll.min.js');
require('ez-ng/dist/ez-ng.js');
require('angular-hotkeys/build/hotkeys.js');
require('angular-ui-tour/dist/angular-ui-tour.js');
```

Do you have any help?

**Comment by benmarch** [comment]
Hey @yoannjauffroy, there have been a few issues with AUIB 2.5.0. I am working on a fix for it, but in the meantime try downgrading to 2.1.x or 2.2.x. I am trying to decouple this library from AUIB since they make breaking changes too often.

Have you tried using the main files for your imports instead of specific files? I wonder if that will help in this case: 
```js
require('angular');
require('angular-sanitize');
require('angular-ui-bootstrap');
require('ngSmoothScroll');
require('ez-ng');
require('angular-hotkeys');
require('angular-ui-tour');
```

**Comment by benmarch** [comment]
I've removed the dependency on AUIB for the next release which will resolve this issue.

**Comment by yoannjauffroy** [comment]
Thanks for your responsiveness @benmarch, I tried to do what you told me but I still have the same mistakes. I think I will retry with the new release

**Comment by benmarch** [comment]
Version 0.8.0 has been released, please verify that this issue has been resolved. Note that there are a few breaking changes that might need to be addressed: https://github.com/benmarch/angular-ui-tour#versions.
