### ISSUE TITLE
TourConfigProvider 'onEnd' with $rootScope

### ISSUE THREAD

**Issue by roly445** [benmarch/angular-ui-tour#12]
Hi,
I have a SPA which I'm trying to put the tour system into.

We have multiple controllers active at on time so I was hoping to broadcast the onEnd event so all controllers can pick up on it.

Have you got any pointers of how to go about this?

**Comment by benmarch** [comment]
Hey @roly445,

My first thought is to create a scope method that you can pass into onEnd, and in the scope method you can use $rootScope.$broadcast(...);

Something like:

    <div ng-controller="AppController">
        <div ui-tour ui-tour-on-end="broadcastEndEvent()">...</div>
    </div>

Then in AppController:

    $scope.broadcastEndEvent = function () {
        $rootScope.$broadcast('tour ended');
    };

Let me know if that works.

**Comment by roly445** [comment]
That seems to work, thanks.

**Comment by benmarch** [comment]
Awesome, closing this issue.
