### ISSUE TITLE
How to add image inside angular bootstrap tour popover

### ISSUE THREAD

**Issue by alex-p-crest** [benmarch/angular-ui-tour#122]
I need to show an image along with content while tour using angular bootstrap tour.

I tried to insert image in to content like this.

 `<button`` ng-show="currentUser['status'] == 'Active' && userAccess['enter-project-name']" class="btn btn-info " type="button" ng-click="addUser();" class="ibox-content text-center" id="step5" tour-step order="5" title="Add Users" backdrop="true" on-Hidden="clearbody(tour)" on-Shown="preparebody(tour)" content="You can create new user with this.<div id = \'image'><img src = 'http://www.google.com/intl/en_ALL/images/srpr/logo11w.png' style='width:600px;height:600px' /></div>" placement="left">Add User</button>`

But it doesn't fit to pop over. I tried to do this by using template-url as well but that is also not proper.

Please suggest some way for this. example with plunker or jsfiddle would be great.

**Comment by benmarch** [comment]
Please provide the version numbers as requested in the PR template. There are also a number of issues such as `on-Shown` instead of `on-shown`, and you have escape characters and backticks in odd places. Both the content and templateUrl should allow for displaying images.
