### ISSUE TITLE
Popover doesn't load properly

### ISSUE THREAD

**Issue by alex-p-crest** [benmarch/angular-ui-tour#123]
I have some other issues.

1. When i apply tour-step-backdrop = 'true' is doesn't cover full screen.
2. When i start the tour the popup comes but empty(not positioned correctly) and when i scroll a bit then it adjust and look properly.

see the screen shot 

![image](https://cloud.githubusercontent.com/assets/16604636/25381188/66bce7bc-29d0-11e7-91d5-e4e150f69cf6.png)

Here is my code 

```
<li ui-sref-active="current" style="width: 33.33%;padding-top:6px;border-top:0" id="step1" tour-step-scroll-parent-id on-Next="checkTour(tour)" tour-step tour-step-order="1" tour-step-title="1 Company Profile" tour-step-backdrop="true" tour-step-on-hidden="clearbody(tour)"  tour-step-content="This is a 1 step on our tour. You can easy set a Company Profile." tour-step-placement="top">

                                    <a ui-sref=".company_profile" class="btn-default ellipsisClass"><span>1</span> Company Profile</a>

                                </li>
```

Please help.

**Comment by benmarch** [comment]
Alex,

Please supply the requested information from the issue template, as well as the browser and browser version.

Couple issues with your code: 
* `tour-step-scroll-parent-id` needs a value (the element ID of the scroll parent)
* `on-Next` needs to be `tour-step-on-next`

Fix those issues and provide the required information, and I will try to help you further.

**Comment by alex-p-crest** [comment]
Actually i don't need both tour-step-scroll-parent-id, tour-step-on-next in my li tag so i have removed them. I used them for testing purpose. The issue still occur.

I noticed something. The transform values were not proper and those set properly when i scroll.So may be the issue with transformation.

**Comment by benmarch** [comment]
I think this is related to #144. Closing this since #144 has more information.
