### ISSUE TITLE
Scrolling is not proper while going previous

### ISSUE THREAD

**Issue by alex-p-crest** [benmarch/angular-ui-tour#125]
This is my first element

```
<li ui-sref-active="current" style="width: 33.33%;padding-top:6px;border-top:0" id="step1"  tour-step tour-step-order="1"  tour-step-prevent-scrolling="true" tour-step-append-to-body="true"  tour-step-title="1 Company Profile" tour-step-backdrop="true" tour-step-on-hidden="clearbody(tour)" tour-step-content="This is a 1 step on our tour. You can easy set a Company Profile." tour-step-placement="top">

                                    <a ui-sref=".company_profile" class="btn-default ellipsisClass"><span>1</span> Company Profile</a>
                                </li>
```

Here is my second element

```
<button  class="btn btn-primary" type="submit" class="ibox-content text-center" id="step2" tour-step="step2" tour-step-prevent-scrolling="true" tour-step-next-step="step3" tour-step-append-to-body="true" tour-step-order="2" tour-step-on-next="navigateToUserAccessRights(tour, 'page2', 'step3')" tour-step-title="Save Company Profile" tour-step-backdrop="true"   tour-step-content="You can save and update Company Profile." tour-step-placement="top">
                Next
            </button>
```

While going previous from second step, due to improper scrolling the scroll does not go to the first step.
Also i have used prevent scrolling so if this happens, then my app get stuck and i can't do anything because no popup visible.

JS used as below:

<script src="bower_components/ngSmoothScroll/lib/angular-smooth-scroll.js"></script>
<script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
<script src="bower_components/ez-ng/dist/ez-ng.js"></script>
<script src="bower_components/angular-hotkeys/build/hotkeys.js"></script>
<script src="bower_components/angular-ui-tour/dist/angular-ui-tour.js"></script>

My Body tag

`<body ng-controller="MainCtrl as main" class="{{$state.current.data.specialClass}} clearfix" ng-class="bodyopacity" landing-scrollspy id="page-top" ui-tour="mytour" ui-tour-use-hotkeys="true" ui-tour-append-to-body="true">`

**Comment by benmarch** [comment]
Closing. Please open another one with the issue template properly filled out.

**Comment by alex-p-crest** [comment]
I have provided everything i have.
