### ISSUE TITLE
placement option not working

### ISSUE THREAD

**Issue by silentFred** [benmarch/angular-ui-tour#13]
Firstly, excellent job @benmarch 

Really enjoying this module so far. Just want to note some bugs as I go along. The placement option on the directive does not seem to work =) I tried the following

placement="bottom"
placement="'bottom'"

I'm happy to help out with these?

**Comment by benmarch** [comment]
Thanks @silentFred! Try using `tour-step-placement="bottom"`. If that's not it then it might be a bigger problem that I will have to look into.

**Comment by dander401** [comment]
@benmarch setting tour-step-pacement does work as a work around. Is there a way I can add it to all steps in a tour programmatically?

**Comment by benmarch** [comment]
Yep, you can add it to the entire tour by using `ui-tour-placement="bottom"` on the tour element, or using `TourConfigProvider.set('placement', 'bottom')` in a config block.

**Comment by dander401** [comment]
@benmarch unless I'm mistaken this sets the option on the tour element which is the option not working atm. Can I set it to the tour steps themselves ( they work just fine ).

Also, this is probably related but I can make another issue if you'd like. I cannot seem to get the tour option appendToBody working.

**Comment by benmarch** [comment]
Ok, let me look into this, I'm not sure what would prevent it from working.

**Comment by benmarch** [comment]
Alright, I am able to reproduce this issue and I think I found the root cause (it would also explain why appentToBody isn't working.) I will fix it and release a patch by tonight (hopefully by midnight GMT-0600). Thank you for bringing this to my attention, and sorry for the inconvenience.

**Comment by dander401** [comment]
thank you for the quick response.

**Comment by benmarch** [comment]
Hi @dander401, it should be working as expected now in 0.3.1. It looks like the tooltips were being initialized _before_ the tour properties were being initialized, so the tour-level properties were not getting passed into $uibTooltip. I replaced the auto-initialize with an event-based initialize so it will wait until everything is ready.
