### ISSUE TITLE
Trouble binding the js to my html page

### ISSUE THREAD

**Issue by oshelke** [benmarch/angular-ui-tour#130]
Hey Ben,
I'm a newbie in Web Development, I'm having problems using you ui-tour plugin, I'm not able to bind your js to my html. I read all the steps you provided but I'm missing something. Please can you let me know how to use it in script as well as match it with my html. 
Please do let me know !!!

**Comment by benmarch** [comment]
@oshelke, what are you unable to do exactly? What have you already done? Please provide much more information in order for me to help you.

**Comment by oshelke** [comment]
Thanks for replying,
I'm practicing the use of angular tours, I was not able to enable tour plugin in my demo page, but I got it done yesterday, what I wanted to do is modify the pop-up template and look, do you have any demo css files for the pop-up as I was having trouble doing so.

**Comment by daotran** [comment]
Hi Ben,
Do you have any example code for demo how to apply your ui-tour plugin?
It will be easier to me to see how it works.

Thanks,
Dao Tran
