### ISSUE TITLE
Second step in multipage tour cannot be seen

### ISSUE THREAD

**Issue by burakkilic** [benmarch/angular-ui-tour#133]
**I am using the _exact_ versions of the following:**

* AngularJS: 1.5.3
* Angular Bootstrap: 1.3.3
* Angular UI Tour: 0.8.1

**I have installed this library via:** (NPM, Bower, or downloaded package)
Bower
**I have observed the following behavior:**

I tried to apply [Multi-page Tour](https://github.com/benmarch/angular-ui-tour#multi-page-tours)
tutorial.
**This is how I expected it to behave:**
The second step cannot be seen.

**Here is my tour config, and all related step configs:**

```js
var tourConfig = {};
```

```html
<body ui-tour ui-tour-backdrop="true" ui-tour-useUiRouter="true" class="page-header-fixed page-sidebar-closed-hide-logo page-container-bg-solid page-sidebar-closed-hide-logo"  ng-class="{'page-sidebar-closed': settings.layout.pageSidebarClosed}">
```

```html
<div id="stepTwo" class="portlet light"  tour-step="stepTwo" tour-step-title="{{'Welcome!' | translate }}" tour-step-content="Let's create your first menu together! Now please click Menu Management."  tour-step-placement="right" tour-step-on-prev="navigateToAndWaitFor(tour, 'shops.dashboard', 'stepOne')" tour-step-order="1">
```

I'm getting Possibly unhandled rejection: No step error from console.

**Comment by benmarch** [comment]
Hey @burakkilic, can you paste in your implementation of `navigateToAndWaitFor()`?

**Comment by burakkilic** [comment]
Hello again,

I realized that DOM is not loaded. I solved that with 1-2 sec timeout.

**Comment by Cidaas** [comment]
vm.gotoTour = function (tour, page, state) {
                 $state.go(state);
                 $.fancybox.close();
            return tour.waitFor(page);
        }

i am getting No step error
