### ISSUE TITLE
Custom tour-step-popup.html

### ISSUE THREAD

**Issue by marcoaure** [benmarch/angular-ui-tour#134]
**I am using the _exact_ versions of the following:**

* Browser: [Chome|Firefox|IE|Safari]
* AngularJS: 1.6.4
* Angular Bootstrap: 2.2.0
* Angular UI Tour: 0.8

**I have installed this library via:** (NPM, Bower, or downloaded package)
Bower
**I have observed the following behavior:**
I need to make a custom tour-step-popup.html becouse I need to put a div before .tourStep

**This is how I expected it to behave:**
I want to custom my tour-step-popup.html

**Comment by benmarch** [comment]
You can create the template and add it to `$templateCache` with the same name (`tour-step-popup.html`). Keep in mind that it is at your own risk to replace that template because I might make breaking changes to it without notice.
