### ISSUE TITLE
tour.on('started') twice after route change

### ISSUE THREAD

**Issue by marcoaure** [benmarch/angular-ui-tour#135]
**I am using the _exact_ versions of the following:**

* Browser: [Chome|Firefox|IE|Safari]
* AngularJS: 1.6.4
* Angular Bootstrap: 2.2.0
* Angular UI Tour: 0.8

**I have installed this library via:** (NPM, Bower, or downloaded package)
Npm

**I have observed the following behavior:**
When I run the page with tour for the first time, it works great, but when I go to another page and return to the tour page, it breaks and displays no errors. I observed that "started" emit is dooing it twice when I return from another page to the tour page. This is my code by example:

```js
if(!uiTourService.getTourByName("sampleName")) {
    uiTourService.createDetachedTour("sampleName");
}

var tour = uiTourService.getTourByName("sampleName");

tour.on('started', function (data) {
    console.log("starting...")
});

if(!tour.hasStep(0)) {

    tour.createStep({
        element: angular.element(document.querySelector("#sampleId")),
        order: 10,
        content: 'sample content'
    });

}

tour.start();
```

This code above is on a controller and the first acess on tour page it console.log starting... 1 time
when I go to another page and return to tour page... it shows "starting" 2 times and the front just breaks, but I get no errors on console... just the funtionality;

**This is how I expected it to behave:**

When I return to the tour page, it should shows again, without layout errors.

**Comment by benmarch** [comment]
Hey @marcoaure, it's because you are attaching a second event listener to the tour. Every time you execute this line, it attaches another listener: 

```js
tour.on('started', function (data) {
    console.log("starting...")
});
```

Be sure to detach your listeners when you are done, probably in a `$destroy` handler:

```js
const onTourStarted = function () {
    console.log('started...');
};

tour.on('started', onTourStarted);

$scope.$on('$destroy', () => {
    tour.off('started', onTourStarted);
});
```
