### ISSUE TITLE
How to make angular-ui-tour to work with angular-translate?

### ISSUE THREAD

**Issue by HenriHeinonen** [benmarch/angular-ui-tour#138]
How to make angular-ui-tour to work with angular-translate?
For example, this piece of code does not seem to work: `<a ng-click="$ctrl.openCreateSiteModal()" tour-step="home-step90" tour-step-belongs-to="teacherTour" tour-step-title="Collection of sites" tour-step-content="<p>{{'HOME-STEP90-1' | translate}}</p>" tour-step-order = "90" tour-step-placement="right" tour-step-prev-step="home-step80">`

**Comment by benmarch** [comment]
Hey @HenriHeinonen, this should be working as of version 0.8.0: https://github.com/benmarch/angular-ui-tour/issues/79

Please fill out the issue template so that I can assist you further.

**Comment by benmarch** [comment]
It looks like dynamic content still wasn't working (although static HTML was). This is fixed in 0.8.2.
