### ISSUE TITLE
Change the current step from code

### ISSUE THREAD

**Issue by roly445** [benmarch/angular-ui-tour#14]
I'm trying to set the current current step via code, but this its not changing the step.

Have you got an example of how to do this?

I can do 'next' and 'prev' but nothing beyond that.

Thanks

**Comment by benmarch** [comment]
Hi @roly445,

Yeah I haven't hooked up a way to jump among tour steps yet. I will add that to my backlog for the next release. Sorry for the inconvenience.

Ben

**Comment by benmarch** [comment]
Releases as tour#goTo(step) in 0.2.0.
