### ISSUE TITLE
Is possible show all tour at once ?

### ISSUE THREAD

**Issue by quocnt** [benmarch/angular-ui-tour#142]
Angular UI Tour: 0.8.2
I have installed this library via: Bower

Hi,
Do you have any plan to add feature "show all tours at once" ?

**Comment by benmarch** [comment]
Hey @quocnt, do you mean show one step each for every tour you created, or all steps for a single tour?

**Comment by quocnt** [comment]
@benmarch I'm sorry, show all steps for a single

**Comment by benmarch** [comment]
Hey @quocnt, I don't have any plans to do that because the intention is that this is a guided tour, so the steps proceed sequentially. May I ask what the benefit of this feature would be?

**Comment by quocnt** [comment]
hi @benmarch,
I'm using this library and have a task in my project so I just ask if if it's supported.

**Comment by benmarch** [comment]
Hi @quocnt, I think the best solution here would be to create multiple tours. You can do that either in the markup with directives or by using the uiTourService with detached tours. Then you can write some logic in your app that will start the tours at the same time.
