### ISSUE TITLE
Double listen to the location change causes tour to be ended.

### ISSUE THREAD

**Issue by RusinovAnton** [benmarch/angular-ui-tour#143]
Hello, thanks for you work on this project, very appreciated.

**I am using the _exact_ versions of the following:**

* Browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
* AngularJS: 1.6.5
* Angular Bootstrap: 2.5.0
* Angular UI Tour: 0.8.2
* Angular UI Router: 0.4.2

**I have installed this library via:** Bower

**I have observed the following behavior:**
I'm using ui-router. After page change these [two events](https://github.com/benmarch/angular-ui-tour/blob/fe3fbecb381230259e44f86393f5e1cbf9b7dc41/app/angular-ui-tour.js#L22-L23) are being triggered separately ('$stateChangeStart' triggers way before '$locationChangeStart').
This causing tour ending after next step on next page showed and tour being resumed.

**This is how I expected it to behave:**

Maybe me doing something wrong? Or we should listen to one event at time, we have `useUiRouter` option, tho? Please halp

**Here is my tour config, and all related step configs:**

```js
TourConfigProvider.enableNavigationInterceptors();
TourConfigProvider.set('backdrop', true);
TourConfigProvider.set('useUiRouter', true);
TourConfigProvider.set('templateUrl', 'views/tour/tour_step.html');
```

```html
tour-step="currentTourStepId"
tour-step-order="3"
tour-step-placement="top"
tour-step-title="CurrentStepTitle"
tour-step-content="CurrentStepContent"
tour-step-on-next="tourRedirect('next.state', { ...nextParams }, 'nextStepId')"
```

```html
tour-step="nextStepId"
tour-step-order="4"
tour-step-placement="right"
tour-step-title="NextStepTitle"
tour-step-content="NextStepContent"
```

**Additional notes/code:**
```
$scope.tourRedirect = function (state, params, nextStepId) {
    if (!$scope.currentTour) {
        return;
    }
    $state.go(state, params);
    return $scope.currentTour.waitFor(nextStepId);
};
```

**Comment by benmarch** [comment]
Hey @RusinovAnton, thank you for providing all of this information and code. I actually never tested this with UIRouter, I added that for backwards compatibility a little while back. Can you try not enabling the interceptors, and then in your app's run block just add the [UIRouter listener](https://github.com/benmarch/angular-ui-tour/blob/fe3fbecb381230259e44f86393f5e1cbf9b7dc41/app/angular-ui-tour.js#L23)? (If you are using UIRouter >= 1.0.0 then use the [other block of code](https://github.com/benmarch/angular-ui-tour/blob/fe3fbecb381230259e44f86393f5e1cbf9b7dc41/app/angular-ui-tour.js#L26-L28) instead.) That way the `$locationChangeStart` event won't effect your tour.

**Comment by RusinovAnton** [comment]
@benmarch, Thanks for quick feedback!
I've just commented this line
```
// TourConfigProvider.enableNavigationInterceptors();
```
without adding anything to the run block and its works. Going to finish guide and test it more. I'll give you more feedback if find anything more.
