### ISSUE TITLE
Repositioning after dynamic content rendering

### ISSUE THREAD

**Issue by cyt-mn** [benmarch/angular-ui-tour#144]
**I am using the _exact_ versions of the following:**

* Browser: Firefox Version: 54.0.1, but also appears in Chrome V 60.0.3112.90
* AngularJS: 1.5.11
* Angular Bootstrap: 3.2.0
* Angular UI Tour: 0.8.0 (commit dfa4dccb706a5ed003a4688088bf4c728108457a)

**I have installed this library via:** (NPM, Bower, or downloaded package)
manually

**I have observed the following behavior:**
I have a tour step in a div and render a table via ng-repeat inside that div. 

**This is how I expected it to behave:**
The position of the popover as well as the backdrop is rendered initially but does not adapt once the table is rendered.

**Here is my tour config, and all related step configs:**

```js
none
```

```html
<div ui-view ui-tour ui-tour-template-url="'frame/view/MyTourTemplate.html'" ui-tour-backdrop-border-radius="4" ui-tour-popup-delay="100"></div>
```

```html
<div tour-step="result" tour-step-title="Result" tour-step-content="Description" tour-step-backdrop="true" tour-step-order="400" tour-step-placement="bottom" tour-step-scroll-into-view="false" tour-step-on-next="detailsEnabled[0] = true;">
    <table>
        <tr data-ng-repeat-start="resultSet in results">
            <td width="35"></td>
            <td>{{resultSet.value}}</td>
       </tr>
    </table>
</div>
```

**Additional notes/code:**
The popover and backdrop are positioned, then the table is rendered. 

![bildschirmfoto 2017-08-08 um 17 45 33](https://user-images.githubusercontent.com/8983165/29080954-7f626b82-7c61-11e7-9bf8-d0c6e7076d13.png)

After resizing the browser, the popover is re-positioned and the backdrop is layouted again - both looking perfectly fine.

![bildschirmfoto 2017-08-08 um 17 45 52](https://user-images.githubusercontent.com/8983165/29080953-7f52d7f8-7c61-11e7-94d0-b2174082aecb.png)

Is there an option to delay the positioning or a function to force repositioning? Besides from that issue everything works great so far...

**Comment by benmarch** [comment]
Hey @cyt-mn, I have observed this issue as well, but I don't have a good solution for it. One thing that works but is a bit hacky is to use `window.scrollTo()` to scroll the window by one pixel and back which will force repositioning. However, I will add a hook in the next release that will allow you to rerender the popover and backdrop.

**Comment by RusinovAnton** [comment]
@benmarch, seems like the `window.scrollTo()` hack doesn't work with bootstrap modals since they're disable body scrolling

**Comment by benmarch** [comment]
@RusinovAnton, is your tour step inside a modal window? I'm working on adding a reposition hook, it should be available this week.

**Comment by RusinovAnton** [comment]
@benmarch yes, it is. I've managed to fix its position with next hacky hack
```
$timeout(function() {
	var currentStep = _.find($rootScope.currentTour._getSteps(), function(step) {
		return step.stepId === nextStepId;
	});

	TourStepService.showPopup(currentStep);
}, 50);
```

> I'm working on adding a reposition hook, it should be available this week.
Sounds great, looking forward to get it!

**Comment by cyt-mn** [comment]
Using the reposition hookup does work. As @RusinovAnton suggested, calling it via $timeout leads to a repositioning after rendering has been completed:

```
$timeout(function(){
                tour.reposition();
            });
```

Thanks @benmarch
