### ISSUE TITLE
which are all necessary requirements to use the library?

### ISSUE THREAD

**Issue by waflessnet** [benmarch/angular-ui-tour#15]
which are all necessary requirements to use the library? the "ezNg" can not find it.

https://github.com/benmarch/angular-ui-tour/blob/55cd2fb4decf54ad586600e9fbb936a3c3713734/dist/angular-ui-tour.js#L12

Thank you

**Comment by benmarch** [comment]
https://github.com/benmarch/angular-ui-tour/blob/master/bower.json#L21-L26

How are you installing this library, out of curiosity?

**Comment by waflessnet** [comment]
I do not use "bower" (by office rules). but this information with me is enough,
 thank you very much.

**Comment by benmarch** [comment]
Ok, I was just thinking about it earlier today... I would like to set this up to be able to install using other package managers, so any information would be useful. Thanks!
