### ISSUE TITLE
Working with modals

### ISSUE THREAD

**Issue by dander401** [benmarch/angular-ui-tour#16]
When I have a modal with a named tour. The tour works as expected, but if the modal is destroyed and brought back, the tour will not display... is there a way to delink it from the old element?

**Comment by benmarch** [comment]
Can you paste in some code or create a Plunkr? Specifically, where is the uiTour directive, how are you initializing it, and are are you using the TourService to grab a reference?

**Comment by dander401** [comment]
sorry im kinda new to actually creating to punker so this wont actually run due to the resources for angular bootstrap not being there. it does have basically what im trying to do though

https://embed.plnkr.co/XiXS0F2Aqb1ZfrN3W0bJ/

when you open the modal, you can start the tour by pressing the button in the modal. the user may leave and come back though and start the tour again.

**Comment by dander401** [comment]
just in case, here is some of my actual code

in the modal view
`<div class="userProfile" ui-tour="userProfileTour">
    <div>
        <h1>Account Settings</h1>
    </div>
    <div class="form-horizontal">
        <div class="form-group" tour-step tour-step-title="Username" tour-step-order="0" tour-step-content="You will use this to log on with" popover-append-to-body="true">
            <label class="col-sm-3 control-label">Username</label>
            <div class="col-sm-8">
                <input class="form-control" name="username" type="string" ng-model="user.username" ng-trim="true" />
            </div>
        </div>
        <div tour-step tour-step-title="Your Name" tour-step-order="1" tour-step-content="This is just so we know who you are" popover-append-to-body="true">
            <div class="form-group">
                <label class="col-sm-3 control-label">First Name</label>
                <div class="col-sm-8">
                    <input class="form-control" name="firstName" type="string" ng-model="user.firstName" ng-trim="true" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Last Name</label>
                <div class="col-sm-8">
                    <input class="form-control" name="lastName" type="string" ng-model="user.lastName" ng-trim="true" />
                </div>
            </div>
        </div>
</div>`

the controller code that starts and stops it
`$scope.close = function() {
                uiTourService.getTourByName('userProfileTour').end();
                $uibModalInstance.close(false);
            };
            $scope.startTutorial = function(){
                uiTourService.getTourByName('userProfileTour').start();
            };`

**Comment by benmarch** [comment]
Thank you, @dander401, that was very helpful. I believe the problem is exactly what you suggested: it is not removing the reference to the old tour. I have now set it up so that the tour is removed from the registry whenever the tour scope is destroyed.
