### ISSUE TITLE
Update Angular dependency version

### ISSUE THREAD

**Issue by michelvosje** [benmarch/angular-ui-tour#162]
**I am using the _exact_ versions of the following:**

* Browser: Chrome Version: 61.0.3163.100
* AngularJS: 1.5
* Angular Bootstrap: ~1.1.0
* Angular UI Tour: 0.8.0

**I have installed this library via:** (Bower)

**I have observed the following behavior:**
Our project uses a very old version of angular v.1.4.8 and angular-ui-tour v0.0.2. I noticed that i can't download v0.0.2 with Bower anymore. So i tried to upgrade to the higher version 0.8.0 which is the only version i can download using Bower.

Now. angular-ui-tour still references to angular version 1.5 and higher. But Angular gives me the following warning:

> angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module rws due to:
Error: [$injector:modulerr] Failed to instantiate module rws.library due to:
Error: [$injector:modulerr] Failed to instantiate module bm.uiTour due to:
Error: [$injector:modulerr] Failed to instantiate module duScroll due to:
Error: [$injector:nomod] Module 'duScroll' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.14/$injector/nomod?p0=duScroll
    at http://localhost:8000/vendor/angular/angular.js:68:12
    at http://localhost:8000/vendor/angular/angular.js:2022:17
    at ensure (http://localhost:8000/vendor/angular/angular.js:1946:38)
    at module (http://localhost:8000/vendor/angular/angular.js:2020:14)
    at http://localhost:8000/vendor/angular/angular.js:4482:22
    at forEach (http://localhost:8000/vendor/angular/angular.js:341:20)
    at loadModules (http://localhost:8000/vendor/angular/angular.js:4466:5)
    at http://localhost:8000/vendor/angular/angular.js:4483:40
    at forEach (http://localhost:8000/vendor/angular/angular.js:341:20)
    at loadModules (http://localhost:8000/vendor/angular/angular.js:4466:5)
http://errors.angularjs.org/1.4.14/$injector/modulerr?

The reason for this seems to be that angular-ui-tour is not compatible anymore with angular v1.5 (i am not surprised...)

**This is how I expected it to behave:**
Make sure that bower.json is regularly updated to the correct latest compatible version of angular.

**Comment by benmarch** [comment]
Hi @michelvosje, I'm not quite sure what state your dependencies are in based on your comments. Are you currently using AngularJS 1.4.8 or 1.5.x? I can see that Angular UI Tour v0.0.2 is still available on Bower, so I'm not sure what is forcing you to upgrade it.

Based on the stack trace it sounds like you have not added the "angular-scroll" script tag to your app. Please see the [Getting Started](https://github.com/benmarch/angular-ui-tour#getting-started) section of the README to get all of the required dependencies.

If possible, please upgrade all of your dependencies to the latest versions, including Angular UI Tour (latest as of now is 0.9.2) which is compatible with Angular >=1.5 (it will probably work with Angular >1.3 though).

**Comment by michelvosje** [comment]
Well i got it fixed. Not sure if there is an issue with Bower or my local Bower installation (i reinstalled npm + nodejs last week). But when downloading Bower packages the download hangs endlessly in my console. I press enter a few times and voila it finished downloading the packages.....
So i wrongly concluded that your 0.0.2 package wasn't available. I've also checked libraries.io and all packages are indeed still available:
https://libraries.io/bower/angular-ui-tour/tags

And you were right about angular-scroll. For some reason when i used angular-ui-tour 0.8.0 it didn't download angular-scroll.

My issues are fixed at this moment. But my local Bower installation is drunk or something...
