### ISSUE TITLE
The backdrop is not working

### ISSUE THREAD

**Issue by EdgarM-** [benmarch/angular-ui-tour#164]
**I am using the _exact_ versions of the following:**

* Browser: [Chome|Firefox] Version: 62.0.3202.94(64-bit)|58.0b6 (64-bit)
* AngularJS: 1.5.7
* Angular Bootstrap: 2.1.2
* Angular UI Tour: 0.9.2

**I have installed this library via:** NPM

**I have observed the following behavior:**
When the popup appears there's no backdrop, also the style is not added

**This is how I expected it to behave:**
When the popup appears that should be backdrop.

**Here is my tour config, and all related step configs:**

```js
var tourConfig = {
"templateUrl",'views/tour-step-template.html'
};
one step
{
            "selector": "body",
            "placement": "left-bottom",
            "order": 0,
            "orphan": true,
            "backdrop": true,
            "appendToBody": true,
            "title": "dashboard_tour_title",
            "content": "Do you want some information about the dashboard?"
        },

**Additional notes/code:**
The tour is code generated.

**Comment by benmarch** [comment]
Hey @EdgarM-,  It looks like this is because your selector is `body`, so the tour is trying to highlight the entire body. Please use a more narrow selector and it should work as expected.

**Comment by EdgarM-** [comment]
Hey @benmarch i tried with a smaller one like a navbar and still is not working, it's like it's not adding the style

```js
var tourConfig = {
"templateUrl",'views/tour-step-template.html'
};
 {
            "selector": "#navbar",
            "orphan": true,
            "order": 0,
            "title":  "Welcome",
            "trustedContent": $sce.trustAsHtml( "{{\"Welcome contentS\"|lang}}")
        },
        {
            "selector": "#navbar",
            "placement": "bottom",
            "order": 1,
            "backdrop": true,
            "appendToBody": true,
            "title": "{dashboard_tour_title}",
            "content": "{Your inventory is always at your fingertips, just type in this search bar}"
        }
```

```html
<nav class="navbar" id="navbar">
        <div class="col-sm-10 col-centered">
            <div class="row">
                <div class="col-xs-7 col-lg-8" id="idSearchBar">
                    <div class="form-group"> 
                        <i class="icon icon-SearchIcon browser"></i>
                        <div id="searchBrowse" class="form-control">
                            <select name="search-browser-widget" id="search-browser-widget" class="select3-seb" multiple="multiple">
                            </select>
                        </div>
                    </div>
                </div>
```
Thanks for the time

**Comment by benmarch** [comment]
Ah I see, you have to add the styles yourself: https://github.com/benmarch/angular-ui-tour#getting-started

Let me know if it still doesn't work after that.

**Comment by EdgarM-** [comment]
Well i didn't add it well in the css, thanks! for your time, another question is there a way to make the title dynamic? example: to translate it and have it in different languages 
Thanks again.

**Comment by benmarch** [comment]
Awesome! If you use the `tour-step` directive to create the tour step then anything you put in the title field will update on every digest. In which case you can pass it an interpolated value and it will reevaluate as needed. For example, you could pass `tour-step-title="{{ 'welcome.step' | i18n }}"` and it will evaluate that at runtime. However, if you create the steps imperatively in your code, then the step configs get passed as static objects to the UI, so it's up to you to update them. This might change in 1.0.0 but I have not finalized a feature list for that yet.

**Comment by benmarch** [comment]
Closing since the original issue was fixed.
