### ISSUE TITLE
Translation Tour

### ISSUE THREAD

**Issue by wiemKh** [benmarch/angular-ui-tour#167]
Hi ben , thank you for the wonderful library :) 
but i have a probleme that i want to translate steps to different languages 
every thing is great exept button (next,prev,pause,end tour)
how can i access this button to modify the code and add for exemple {{prev | translate }}

**Comment by benmarch** [comment]
Hey @wiemKh, you can copy the template from here: https://github.com/benmarch/angular-ui-tour/blob/master/app/templates/tour-step-template.html

Then modify it and save it somewhere that your app can get it (either by adding it to $templateCache or making it available for request) and use the `templateUrl` option to point to it.

**Comment by wiemKh** [comment]
thank you :)
