### ISSUE TITLE
Not Organised Tour 

### ISSUE THREAD

**Issue by wiemKh** [benmarch/angular-ui-tour#168]
hi ben, please i have a probleme very urgent to be resolved :(
i'am using Multi-page Tours 
the problem is when the user do not click on next button of the tour and click on another button on the project par exemple home , when he redirected to the home page the tour step of the  other page  still displayed .
index.html :  <body ui-tour  ui-tour-use-hotkeys="true"  ui-tour-template-url="'views/tour-step-template.html'"
controller:
function TourCtrl($scope, $state) {

    $scope.navigateToPlansList = function (tour, state, stepId) {
        $state.go(state);
        return tour.waitFor(stepId);
    }
view1:
```
<div ng-controller="TourCtrl" ><div tour-step="projects.projectsList" tour-step-title="" tour-step-content="" tour-step-order="1" tour-step-placement="left" tour-step-on-next="navigateToPlansList(tour,'plans.plansList','plans.plansList')"></div> </div>
```
view2:
```
<div  ui-tour-template-url="'views/tour-step-template.html'  ng-controller="TourCtrl" 
<div  tour-step-placement="left" tour-step-title="" tour-step-content=""      tour-step="plans.plansList" tour-step-order="2" tour-step-on-prev="navigateToPlansList(tour,'projects.projectsList','projects.projectsList')"          
 tour-step-on-next="navigateToPlansList(tour,'plans.plansList','plans.plansList')"></div></div>
```
thank you for ur time.

**Comment by wiemKh** [comment]
view1:
<div ng-controller="TourCtrl" >
<div id="projects.projectsList"  tour-step="projects.projectsList" tour-step-title="" tour-step-content="" tour-step-order="1" tour-step-placement="left" tour-step-on-next="); navigateToPlansList(tour,'plans.plansList','plans.plansList')"></div> </div>

view2:
 <div  ui-tour-template-url="'views/tour-step-template.html'  ng-controller="TourCtrl" ng-if="$first"  <div id="plans.plansList" tour-step-placement="left" tour-step-title="" tour-step-content=""      tour-step="plans.plansList" tour-step-order="2" tour-step-on-prev="navigateToPlansList(tour,'projects.projectsList','projects.projectsList')"
                                                tour-step-on-next="navigateToPlansList(tour,'plans.plansList','plans.plansList')"></div></div>

**Comment by benmarch** [comment]
Please read the Getting Started section of the README: https://github.com/benmarch/angular-ui-tour#getting-started

```js
module.config(function (TourConfigProvider) {
    TourConfigProvider.enableNavigationInterceptors();
});
```
