### ISSUE TITLE
Button Next Doesnt Work

### ISSUE THREAD

**Issue by syndra123** [benmarch/angular-ui-tour#169]
hi thank you for this library.
i have a question , i'am using multiple view tour
for the need of my project when i called the function navigateToAndWaitFor with tour-step-on-next
i want to call another function for exemple

```
 <div tour-step="" tour-step-title="" tour-step-content=""
                                                 tour-step-order="3" tour-step-on-
                                                tour-step-on-next=" navigateToAndWaitFor(tour,'/customer/customerDetail','cust');goToCustomer()"></div>
                                        </div>
```

it worked well before i add    TourConfigProvider.enableNavigationInterceptors();   on the config 

but i must add    TourConfigProvider.enableNavigationInterceptors();   what should i do?

**Comment by benmarch** [comment]
Hey @syndra123, `navigateToAndWaitFor()` is an example that I created for the README, but you can call any function for the onNext hook. Just put `goToCustomer()` in your handler function.
