### ISSUE TITLE
How to get tour name

### ISSUE THREAD

**Issue by plasensa** [benmarch/angular-ui-tour#173]
Hello,

I have been able to get everything working using tour names and calling tour names as needed. But my problem comes when I am using tour.start() in a button that displays in all the screens to start the tour of the page where I am. The tour starts without any problem, however I am unable to get the tour name.

I have tried a lot of times using getTour() in different ways, but all the data returned is empty and nothing from where I can get the name of the tour that has been triggered. Can anybody help me out here?

Thank you in advance

**Comment by valentina91p** [comment]
It seems like there isn't a way to know which tour was triggered, since getTour will always return the first  one (regardless of whether it is active or not), and you already have to know the name for getTourByName to work. From where are you trying to get the tour's name?

**Comment by benmarch** [comment]
@plasensa, if you have a reference to the tour object, just look up `tour.options.name`.
