### ISSUE TITLE
Unable to block navigation using Tab (keyboard)

### ISSUE THREAD

**Issue by ShruVish** [benmarch/angular-ui-tour#177]
**I am using the _exact_ versions of the following:**

* Browser: Chrome
* AngularJS: 1.5.5
* Angular UI Tour: 0.9.2

I have installed this library via: NPM

I have enable the backdrop i.,e backdrop: true and 
.ui-tour-backdrop {
background-color: rgba(0, 0, 0, 0.5);
fill: rgba(0, 0, 0, 0.5);
} in the CSS. 

I do see the backdrop applied to my application. However, I am able to navigate through the application using tab (keyboard). I want to block the navigation by tab.

**Comment by benmarch** [comment]
Do you mean you can still focus on elements behind the backdrop using the tab key like a user with accessibility issues might do? Or do you mean that you can navigate to the next tour step by pressing the tab key?

**Comment by ShruVish** [comment]
I am able still focus on elements behind the backdrop using the tab key. Sorry, for not being specific about that.

**Comment by benmarch** [comment]
Ok, as far as I know, there isn't anything I can do about that. I did add accessibility controls so that the tour step is focused when it first opens, and when the tour stops, the last-focused element is refocused. I would recommend implementing that yourself if it is possible.
