### ISSUE TITLE
Incompatibility with browserify

### ISSUE THREAD

**Issue by muliyul** [benmarch/angular-ui-tour#189]
**I am using the _exact_ versions of the following:**

* Browser: [Chome] Version: 68
* AngularJS: 1.6.4
* Angular UI Tour: 0.9.2

**I have installed this library via:** (NPM, Bower, or downloaded package)
npm

**I have observed the following behavior:**
>Cannot find module '!!../../node_modules/css-loader/index.js!./angular-ui-tour.css' from '/Users/\*/projects/\*/node_modules/angular-ui-tour/dist'.

I substituted some of the path so ignore asterisks.

**This is how I expected it to behave:**
Bundle correctly with browserify

**Here is my tour config, and all related step configs:**
Irrelevant

Here's how I import AUIT: `require('angular-ui-tour');`
I've also attempted to use `require('angular-ui-tour/dist/angular-ui-tour');`

**Additional info:**
By removing these lines from the dist file I was able to require the file correctly so perhaps a webpack config issue?
```
// file: dist/angular-ui-tour.js lines 196-207
if(false) {
	// When the styles change, update the <style> tags
	if(!content.locals) {
		module.hot.accept("!!../../node_modules/css-loader/index.js!./angular-ui-tour.css", function() {
			var newContent = require("!!../../node_modules/css-loader/index.js!./angular-ui-tour.css");
			if(typeof newContent === 'string') newContent = [[module.id, newContent, '']];
			update(newContent);
		});
	}
	// When the module is disposed, remove the <style> tags
	module.hot.dispose(function() { update(); });
}
```

**Comment by benmarch** [comment]
Hey @muliyul, sorry for the long delay. Thank you for pointing this out, I released patch 0.9.4 to fix this.
