### ISSUE TITLE
Usage Enquiry

### ISSUE THREAD

**Issue by mubinahmed** [benmarch/angular-ui-tour#194]
Hi @benmarch, 

The last commit was quite a long time back. I believe the library might not be compatible with latest versions of Angular anymore (of course, it is an assumption without spending any time on trying out first).

Can you or any other member here confirm if this library is in a shape to be updated for usage with latest Anuglar version?
If not, is somebody aware of an alternative with the same possibilities as this library?

**Comment by benmarch** [comment]
Hey @mubinahmed, sorry I no longer maintain this project. It uses the original Angular 1.x, so it's significantly outdated.
