### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by piernik** [benmarch/angular-ui-tour#2]
Can You provide a simpliest  codepen demo?

**Comment by benmarch** [comment]
Hey @piernik have you looked into the demo in the repo yet? https://github.com/benmarch/angular-ui-tour/tree/master/demo

**Comment by piernik** [comment]
Yes I did and still can't get it working - link to working demo in readme would be great.

**Comment by benmarch** [comment]
I've created a simple codepen for you: http://codepen.io/anon/pen/JGoqNq

If you can paste here some of you code and/or any errors you are getting I can try to help you.

**Comment by piernik** [comment]
Thanks. I was looking for  `tour.start()`. It's not mentioned in readme.

Is it possible to start tour with service?

I've got problem. Here is code pen:
http://codepen.io/piernik/pen/pgvMrE

As You see order is wrong as well as second step

**Comment by benmarch** [comment]
Yeah it looks like the order is getting messed up, I will open another ticket for that. The orphan steps haven't been implemented yet (see the README). I am going to close this out and create 2 more tickets: 1 for fixing the order, and one for documenting the Tour API. I should be able to get to it this weekend.
