### ISSUE TITLE
Remembering which step the user was

### ISSUE THREAD

**Issue by cesarcosta99** [benmarch/angular-ui-tour#21]
I'm trying to set this functionality with local storage variables by this way:

```html
<div ui-tour ui-tour-on-ready="onTourReady(tour)" ui-tour-on-show="onTourStep(tour)" ui-tour-on-end="onTourEnd()" ui-tour-popup-delay="1000"></div>
```

```javascript
$scope.onTourReady = function (tour) {
  $scope.$on('startTour', function () {
    $state.go('app.dashboard');
    tour.start();
    $window.localStorage.setItem('tour_ended', 'false');
  });

  if ($window.localStorage.getItem('tour_ended') === 'false' && $window.localStorage.getItem('tour_current_step')){
    tour._setCurrentStep($window.localStorage.getItem('tour_current_step'));
    tour.start();
  }
};

$scope.onTourStep = function (tour) {
  $window.localStorage.setItem('tour_current_step', tour._getCurrentStep().stepId);
};

$scope.onTourEnd = function () {
  $window.localStorage.removeItem('tour_current_step');
  $window.localStorage.removeItem('tour_ended');
};
```
Is that possible?
Edit: The tour initiates from the start if I try to `start` and I'm getting error at `self.showStep` (angular-ui-tour.js:373) and at angular-ui-tour.js:546 if I try to `resume`.

Other thing I tested was backdrop, for me it's not working so well. Sometimes the backdrop is overriding the screen and the backdropped element is **staying** on the screen after going to other step.

**Comment by benmarch** [comment]
If you are going to use the stepId, make sure your step's ID is explicitly set by providing a value to the tour-step attribute: `tour-step="<stepId>"`. Also, if your steps are on a dynamically added view you will have to wait for that to load. Can you paste the stack traces in? I'm not sure what would cause errors there.

Try changing:

```js
tour._setCurrentStep($window.localStorage.getItem('tour_current_step'));
tour.start();
```

To:

```
tour.start();
tour.goTo($window.localStorage.getItem('tour_current_step'));
```

**Comment by cesarcosta99** [comment]
All steps are defined with tour-step attribute and the views are been loaded before.
I tried what you told and the tour is starting from the beginning.

Here are the exceptions (trying with `_setCurrentStep` and `resume()`):
On `self.hideStep` function, `step.config('onHide')` at line 411:37;
On `self.hideStep` function `self.goTo` at line 626:25.

**Comment by benmarch** [comment]
Ah ok this makes sense. So yeah try to avoid _setCurrentStep() because it actually doesn't do what it sounds like, and resume() will only work if the tour is paused. I think this might need to be a new feature where you can start the tour at a specific step. I will add this to the next release. Would you prefer to use the existing start() method and pass in an optional step, or have a new method called startAt(step)?

**Comment by cesarcosta99** [comment]
Sure! I think the new method `startAt(step)` would be better, but what you to prefer is fine! Thanks @benmarch

**Comment by benmarch** [comment]
Hey @cesarcosta99, I have exposed the `tour.startAt(step)` function in 0.4.0. You can pass any index, step ID, or step object that you would like to start on. I have also exposed `tour.getCurrentStep()` which will return a copy of the current step. As long as the stepId is set, you can use this copy in the startAt() function and any other function that accepts a step. You can also use any of the new events (see the README for details) to receive lifecycle updates from the tour which might be useful for storing state.

**Comment by cesarcosta99** [comment]
Awesome @benmarch! Thank you very much and the new events are very useful, great job with the plugin! I'll test it later.

**Comment by cesarcosta99** [comment]
It's working fine @benmarch, but I had to remove the `angular.copy()` that was coming with the emitters to work properly, were illegal declarations, the objects were losing their references. Don't forget to update the documentation about `startAt()`, the world needs to know that hahaha, and thank you again!

**Comment by benmarch** [comment]
Thanks for the reminder, @cesarcosta99, I'll document that asap! I had used copy very intentionally to prevent modification to the actual tour steps, but since the steps are exposed on the scope anyway I might just return the original steps. How exactly are you using them so that I can better make a decision about how to handle them?

**Comment by cesarcosta99** [comment]
I understood your point, but the objects were losing their references, so didn't worth it, I had to remove **all** `copy` from controller, only left one from the service.
My use:
```javascript
$scope.onTourReady = function (tour) {
  $scope.$on('startTour', function () {
    $state.go('app.dashboard');
    tour.start();
  });
  if ($localStorage.tour_current_step){
    $state.go($localStorage.tour_current_step.state);
    $window.setTimeout(function(){
      tour.startAt($localStorage.tour_current_step.step);
    },0);
  }
};
$scope.onTourStep = function (tour) {
  $localStorage.tour_current_step = {
    step: tour._getCurrentStep().stepId,
    state: $state.current.name
  };
};
$scope.onTourEnd = function () {
  delete $localStorage.tour_current_step;
};
```

**Comment by benmarch** [comment]
Interesting, it looks like it would be ok in this case because you are just using the stepId, but maybe I am missing something. I think I will just make the critical properties read-only and return the actual step reference. Thank you for your help!
