### ISSUE TITLE
Mobile issue

### ISSUE THREAD

**Issue by rdbauer** [benmarch/angular-ui-tour#22]
I found this plugin and it looks and works great from what I can tell this far. I am looking forward to getting to use it on our project. I was just viewing the demo tour on my phone and noticed that the 4th step (the start of the table) has the "tooltip" off to the left. While I don't remember having any issue with it on my desktop yesterday, on my phone it is off the screen and I have no way of "scrolling over" to it or anything, hence leaving me unable to continue or close the tour. I have no current tests with it or fixes as of yet. I just didn't know if you were aware of this and if it is a bug or just a styling issue that I will have to avoid when I implement this.

Great work!

**Comment by benmarch** [comment]
Hi @rdbauer, I noticed a similar issue the other day when I had a 100%-width div and positioned the step to the left. I am currently using Angular UI's tooltips to handle the position for me, so I wonder if there is a configuration option to prevent them from appearing off screen. I will look into this and see if it can be done out of the box. If not, I'll add it to the back log for the next releases. Using a top- or bottom-positioned step should prevent this in the meantime.

Thanks,
Ben

**Comment by rdbauer** [comment]
That is what I was figuring. I did read that angular-ui is working on it. Discussion is in angular-ui/bootstrap#4762.

**Comment by benmarch** [comment]
Yeah I might just wait for them to fix it. I tried using "auto left" per their recommendation but it really doesn't right.

**Comment by benmarch** [comment]
I played around with this a bit over the weekend, but because of its complexity, and the fact that the UI team is already working on it, I am going to leave it to them. Thank you for your interest in this plugin!
