### ISSUE TITLE
scope access view on div

### ISSUE THREAD

**Issue by waflessnet** [benmarch/angular-ui-tour#23]
I am try create tour, when change select send other step, but not access to scope of controller example in controller the $scope.Rubro always is null , but  delete tag tour-step the $scope working properly: 

```javascript

app.config(function(TourConfigProvider,$stateProvider, $urlRouterProvider) {
  ...
  //tour 
  TourConfigProvider.set('scrollOffset', 200);

        TourConfigProvider.set('onStart', function () {
            console.log('Started Tour');
        });
        TourConfigProvider.set('onNext', function () {
            console.log('Moving on...');
        });
 $stateProvider
.state('prueba',{
    	url:'/prueba',
      params: {
          xxxx :2, 
      },
      controller: 'pruebaCtrl', 
    	templateUrl: "/xxxxx/xxxxx/xxxxxx/template.html"
  })
app.controller('pruebaCtrl', function ($scope,$http,$state) {
  ...
$scope.clickRubro = function(){
  ...
// value $scope.Rubro is null , but if not use tour directive in div, the scope.Rubro is correct 
        $http.get('/xxxxx/xxxxx/'+$scope.Rubro).success(function(data){ 
           if(!angular.isArray(data.item)){
              $scope.selProducto.push(data.item);
            }else {
              $scope.selProducto = data.item;  
            }
          $scope.loading = false;
       });

    }
});
```

layout: 
```html
<body ui-tour>
<aside tour-step="'PH'" tour-step-title="Bienvenido!" tour-step-content="Este tour tratará de explicarle como utilizar la herramienta!" tour-step-order="0" tour-step-orphan="true" tour-step-backdrop="true">
</aside>
....
<div class="row">
        <div ui-view></div>
     </div>
```
view template.html

```html
<div class="form-group" tour-step="'PH'" tour-step-title="ejemplo" tour-step-content="Seleccione rubro" tour-step-order="10" tour-step-orphan="false" tour-step-backdrop="true"  tour-step-fixed="false">
                  <label for="sector" class="Tit_verde">Rubro:</label> 
                  <select  size="1" class="menu_lista form-control" ng-model="Rubro" ng-options="item.IDCategoria as item.Rubro for item in selRubro" ng-change="clickRubro();" ></select>
                </div>
```
to try add  tour.next(), but generate error  not found config etc.
```html
<select  size="1" class="menu_lista form-control" ng-model="Rubro" ng-options="item.IDCategoria as item.Rubro for item in selRubro" ng-change="clickRubro(); tour.next()" ></select>
```

which is the correct way to access the scope of controller? by  example  in controller 'pruebaCtrl' , and/or how access to directive tour for next when change select ,
 very thanks !

**Comment by benmarch** [comment]
Hi @waflessnet, this is most likely throwing an error because somewhere there is an isolate scope that does not inherit `$scope.tour`. I think the best way for you to access the tour in this case is by using TourService like this:
```js
app.controller('prueboCtrl', [..., 'TourService', function (..., TourService) {
    $scope.clickRubro = function () {
        var tour = TourService.getTour();
        tour.next();
    }
}]);
```

Hopefully this helps, let me know if it still is not working.

Thanks,
Ben

**Comment by waflessnet** [comment]
@benmarch  thanks ! i try, but : 
![image](https://cloud.githubusercontent.com/assets/6413704/13925456/23c23d8a-ef67-11e5-82a7-c54e484442dd.png)

my js : 
```javascript
app.controller('SeguroAgricolaCtrl',['$scope','$http','$state','parametrosService','$stateParams','$interval','$uibModal','TourService', function ($scope,$http,$state,parametrosService,$stateParams,$interval,$uibModal,TourService) {
  ...
}]);
```
the service not found :walking:

**Comment by benmarch** [comment]
Sorry, my fault, it should be "uiTourService" (I forgot I changed the names recently).

**Comment by waflessnet** [comment]
jaja perfect ! thanks, the service is correct. 
how can control event in div selected  example: 
![image](https://cloud.githubusercontent.com/assets/6413704/13929646/e6fe51be-ef79-11e5-97ee-a47aa091287b.png)

when used in div tour-step, the events in controller  not work , is posible call a handle ? , 
by example  in select the event ng-change="clickRubro();":
```html
 <div class="col-xs-4 col-sm-4 col-md-4">
                <div class="form-group" tour-step="'PH'" tour-step-title="Seguros Pecuarios" tour-step-content="Seleccione rubro" tour-step-order="20" tour-step-orphan="false" tour-step-backdrop="true"  tour-step-fixed="false">
                  <label for="sector" class="Tit_verde">Rubro:</label> 
                  <select  size="1" class="menu_lista form-control" ng-model="Rubro" ng-options="item.IDCategoria as item.Rubro for item in selRubro" ng-change="clickRubro()" ></select>
                </div>
              </div>
```

thank you very much for your help.

**Comment by benmarch** [comment]
Awesome! Unfortunately, you won't be able to use any scope items when you use the backdrop. The backdrop causes the element to be cloned, which causes it to lose all ties to the original element and scope. I can try to change it so that it will use the original scope, and if it is possible then I will add it to the next release. For now, try removing the backdrop and see if that works for you.

Thanks,
Ben

**Comment by waflessnet** [comment]
OMG :+1:  work !  backdrop=false :D 
great job ! 
thanks for sharing
