### ISSUE TITLE
Prevent scrolling problem with cloned element

### ISSUE THREAD

**Issue by cesarcosta99** [benmarch/angular-ui-tour#27]
When the backdrop is activated the cloned element is _backdropped_ fine, but when prevent scrolling is activated occurs variations in the width and x-position of the cloned element. His height and y-position seems fine.

**Comment by benmarch** [comment]
Hey @cesarcosta99, please include screen shots/code snippets/steps to reproduce.

**Comment by cesarcosta99** [comment]
My bad, but I discovered what it is, it occurs because of the `overflow: hidden` on body's style `no-scrolling` and causes variation in the width/height/positioning depending on x/y scroll. As the steps continue the variation grows (with backdrop in all tour).

**Comment by cesarcosta99** [comment]
Solved just moving up prevent scrolling call to the top of function `service.createForElement` because is before $uibPosition make the calculations.

**Comment by benmarch** [comment]
Hey @cesarcosta99, I'm sorry I'm not really following what you are describing. Can you include screenshots and markup, please? And it sounds like you modified the library code, can you include snippets of that as well?

**Comment by cesarcosta99** [comment]
I'm sorry if I wasn't clear enough, but I'm talking about that:
![captura de tela de 2016-03-24 13 23 38](https://cloud.githubusercontent.com/assets/10233985/14023701/5501ad72-f1c4-11e5-92ed-dcd8e785a8b9.png)

The tour wrapper: `<div ui-tour ui-tour-backdrop="true" ui-tour-append-to-body="true"></div>`
And all the steps have `tour-step-prevent-scrolling="true"`.

I'll make a PR in the weekend for you to see what I changed.

**Comment by benmarch** [comment]
Hey @cesarcosta99, I see what you mean about it not aligned properly. It might have something to do with the margin/padding of original element. Can you paste the CSS (all of the computed CSS) here and I will see if I can reproduce?

**Comment by cesarcosta99** [comment]
No, it haven't, the problem happens because the flow of add/remove class and I can't because I'm not cloning the element anymore, I create a blank div and apply a box shadow. I'll make the PR, wait for it! :grin:

**Comment by benmarch** [comment]
Ok, thanks!

**Comment by cesarcosta99** [comment]
Hey @benmarch I made the PR #31, take a look and test it, please.

**Comment by benmarch** [comment]
Thanks, @cesarcosta99, just commented. I will take a look this weekend and respond.

**Comment by benmarch** [comment]
Hey @cesarcosta99, can you install pre-release 0.5.0-rc.1 and test that the changes are working for you as expected? Thanks!

**Comment by cesarcosta99** [comment]
Hey @benmarch, I installed and worked as expected in my project, but I saw you added the hotkeys and they didn't work for me. I'll close this issue since preventing scrolling problem was solved. Thanks!

**Comment by benmarch** [comment]
Sweet, thanks! I'll look into and option to prevent interaction during the tour. The hotkeys are disabled by default, but if you set useHotkeys to true it should work.
