### ISSUE TITLE
Fix issue with step ordering

### ISSUE THREAD

**Issue by benmarch** [benmarch/angular-ui-tour#3]
Looks like having nested steps might affect the order but it shouldn't.

**Comment by piernik** [comment]
Any news on this?

**Comment by piernik** [comment]
Hello?

**Comment by benmarch** [comment]
@piernik I'm so sorry for the long delay, I had a fix for it a while ago but never committed it. I have created a prerelease for you to test, and if that works I will do a full release. Please use version 0.0.3-rc.1 to test the changes and let me know if it works.
