### ISSUE TITLE
preventScrolling Firefox

### ISSUE THREAD

**Issue by AlexanderVielhauer** [benmarch/angular-ui-tour#30]
Hi,

I am using preventScrolling and it works fine in Chrome, but it's hell of a mess in Firefox...
`ui-tour ui-tour-backdrop=true`

`<div 	tour-step
	    tour-step-title="title"
	    tour-step-content="content"
	    tour-step-order="1"
	    tour-step-placement="top"
	    tour-step-fixed=true
	    tour-step-orphan=true
      tour-step-preventScrolling=true>
</div>`

I have a page without x or y-scroll and want to give a tour on it, so no scrolling at all. On Firefox it keeps scrolling my content up and copying the element at another place, like this: https://i.gyazo.com/1c57105299695d2c394c49b1352a4fd9.png (the original element is the upper one and all my page content is above the upper one)

**Comment by benmarch** [comment]
You have some clashing options set. Try removing orphan (since it's not an orphan) and make sure you are using `tour-step-prevent-scrolling` and not `tour-step-preventScrolling`. Only set fixed if the element or any of its ancestors are `positioned: fixed;`.

**Comment by AlexanderVielhauer** [comment]
Sorry, the one I quoted was for another div than shown on the screenshot. I fixed the `preventScrolling` one and removed fixed since it has `position: absolute`. However, it still keeps scrolling down: https://i.gyazo.com/e39407f03e9007c435f00f33742be13e.png

**Comment by benmarch** [comment]
Can you include a before screen shot (before you show the step) that is aligned with the one you just provided? Or if you could provide a screen recording of what happens why you show the step that would be even better. It's difficult to understand the behavior with a single screenshot.

**Comment by AlexanderVielhauer** [comment]
You can try it out here: http://ggalex.fomalhaut.uberspace.de/#/Azoth123 (try in Chrome+Firefox)

Here's the tour: `<body ng-app="helpstoneApp" ui-tour ui-tour-backdrop=true ui-tour-append-to-body=true>`

The first step: `<div 	tour-step
	    tour-step-title="step1"
	    tour-step-content="cnt1"
	    tour-step-order="1"
	    tour-step-placement="top"
	    tour-step-orphan=true
      tour-step-prevent-scrolling=true>
</div>
`

Any step after this has the following form: `<div
      tour-step
      tour-step-title="title"
      tour-step-content="content"
      tour-step-order="2"
      tour-step-fixed=true
      tour-step-placement="top"
      tour-step-prevent-scrolling=true>
</div>`

**Comment by benmarch** [comment]
Ok cool, thanks. It looks like `fixed` is breaking it in FireFox, can you remove it so I can see what is going on in Chrome?

**Comment by AlexanderVielhauer** [comment]
I removed fixed for the 2nd step. So it looks like this: `<div  class="footer-info-tour"
      tour-step
      tour-step-title="Always here!"
      tour-step-content="If you want to learn about other features or pick up the tour again, you can click here any time."
      tour-step-order="2"
      tour-step-placement="top"
      ng-click="infoTour()">
  <img src="images/info.png">
  Helpstone Tour
</div>`

All other steps are unchanged. Let me know if I should change some more.

**Comment by benmarch** [comment]
Alright, my suggestion for now is to remove `prevent-scrolling` because you don't need it on your site. I will enhance the feature to prevent the issue that you are seeing, but I think you can avoid it by not using it. Let me know if the behavior is what you expect after removing it.

**Comment by AlexanderVielhauer** [comment]
So removing `prevent-scrolling` and `fixed` from all steps? What about `backdrop` and `append-to-body` in the `ui-tour`?

**Comment by benmarch** [comment]
Yes, remove both. Leave backdrop if you want the backdrop, and leave appendToBody if you keep backdrop.

**Comment by AlexanderVielhauer** [comment]
Hm, removed `backdrop` and `append-to-body` and the first to steps look like this now:
`<div 	tour-step
	    tour-step-title="Helpstone Tour"
	    tour-step-content="Hi there! If you are new to Helpstone, you should take this tour to get a quick overview of all its features."
	    tour-step-order="1"
	    tour-step-placement="top"
	    tour-step-orphan=true>
</div>`

`<div  class="footer-info-tour"
      tour-step
      tour-step-title="Always here!"
      tour-step-content="If you want to learn about other features or pick up the tour again, you can click here any time."
      tour-step-order="2"
      tour-step-placement="top"
      ng-click="infoTour()">
  <img src="images/info.png">
  Helpstone Tour
</div>`

It still scrolls down for the second step. :/

**Comment by benmarch** [comment]
It looks like that is caused by the `overflow: hidden;` on the body tag. If you remove that and find a way to ensure that the body does not overflow the viewport then it won't be able to scroll. I will also add a flag in the next release that you can set so that the tour doesn't automatically scroll to the step.

**Comment by AlexanderVielhauer** [comment]
I removed the `overflow: hidden` and it still doesn't behave as expected. I added the prevent-scrolling stuff again (because now there are scroll bars for the body), but it doesn't help it. Chrome scrolls only a bit, but Firefox still scrolls a chunk. I'll revert back to the version that worked 100% fine on Chrome and link other browsers a video of the tour for now. :P

**Comment by benmarch** [comment]
Ok, basically what's going on is your page by default does exactly what `preventScrolling` does when it is enabled: it hides the overflow of the `<html>` and `<body>` elements which makes it appear like there is nothing to scroll to. However, there is content to scroll to, it's just hidden. So although the user cannot scroll, it doesn't mean that there is no content to scroll to, and the tour is able to scroll to it. My last suggestion is to set the scroll offset for the step to be very large (like 10000) which should cause the tour to attempt to scroll up (which it can't do because there is no content above). I still recommend not using preventScrolling because you don't need it since you already have that enabled on your page. Use the backdrop and appendToBody, definitely don't use fixed. Setting the offset (see the README for documentation) should fix the problem.

**Comment by AlexanderVielhauer** [comment]
Sorry, what part of the docu are you refering to? Do you mean the normal HTML scroll offset or something for the tour framework?

**Comment by benmarch** [comment]
The tour scroll offset. See the README.

**Comment by AlexanderVielhauer** [comment]
Urgh, I'm sorry, I cannot find an option in the README that is about scroll offset. Searching for "scroll" only hits for preventScrolling.

**Comment by benmarch** [comment]
Ahh jeez I'm sorry, it looks like it isn't documented! I'm using it in the demo, but basically you can set it like `tour-step-scroll-offset="5000"` on that step. I'll make a note to document that option, thanks for pointing it out.

**Comment by AlexanderVielhauer** [comment]
Haha, alright. Already felt like an idiot to keep asking. :P

**Comment by AlexanderVielhauer** [comment]
Sweet, it works just fine now. Thanks a lot. `tour-step-scroll-offset` did the trick.

**Comment by benmarch** [comment]
Awesome! Sorry for the confusion over the documentation!
