### ISSUE TITLE
Readme is not clear

### ISSUE THREAD

**Issue by luxueyan** [benmarch/angular-ui-tour#33]
![image](https://cloud.githubusercontent.com/assets/1555552/14066385/9e89c7fa-f47a-11e5-81ca-158f99f30afc.png)
Your module depend on ngSmoothScroll' ' 'ez-ng', but the readme is not clear!

**Comment by benmarch** [comment]
Yes, the readme is definitely out-of-date and I am in the process of updating it. 

For my knowledge, how are you installing this module? I am going to try to make it more universally installable, but I need to know how others are currently installing it.

**Comment by luxueyan** [comment]
I use bower. Maybe it is not a good choice as times go on

**Comment by benmarch** [comment]
Yeah, unfortunately Bower looks like it's on its way out. It took me a long time to warm up to it, and now I'm having a hard time letting it go. I think it will still be around for a couple years, so I would recommend using wiredep along with it (check out the gruntfile.js in this project for an example). Anyway, I updated the readme per your suggestion. Thanks for pointing it out!
