### ISSUE TITLE
Popover doesn't appear if element is disabled

### ISSUE THREAD

**Issue by cesarcosta99** [benmarch/angular-ui-tour#35]
Hey @benmarch, if I have a step in an element with `ng-disabled` that catches `true` or `disabled="disabled"` the popover doesn't appear, like: 
```html
<button data-ng-click="doSomething()" class="btn" data-tour-step data-tour-step-order="2" data-tour-step-prevent-scrolling="true" data-tour-step-placement="left" data-tour-step-content="This button do something." data-ng-disabled="form.$invalid">Do something!</button>
```
The backdrop of this element and the other popovers are shown normally.

**Comment by benmarch** [comment]
Hey @cesarcosta99, this is actually an issue with the Angular UI Tooltip directive; it uses DOM events to trigger tooltips, which don't fire on disabled elements: https://github.com/angular-ui/bootstrap/issues/1025

Probably best to just wrap the button in another element and put the tour step on that, or use other means of preventing the button's action. Sorry for the inconvenience, I know this isn't ideal.

**Comment by cesarcosta99** [comment]
Relax @benmarch, it's not your fault, I realized that was a angular-ui problem after submit this issue, but thanks anyway! :+1:
