### ISSUE TITLE
The demo is broken (probably b/c of 404s)

### ISSUE THREAD

**Issue by stodolos** [benmarch/angular-ui-tour#36]
> GET http://benmarch.github.io/angular-ui-tour/bower_components/angular-hotkeys/build/hotkeys.css 404 (Not Found)
> (index):81 GET http://benmarch.github.io/angular-ui-tour/bower_components/angular-hotkeys/build/hotkeys.js 
> angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module uiTourDemo due to:
> Error: [$injector:modulerr] Failed to instantiate module bm.uiTour due to:
> Error: [$injector:modulerr] Failed to instantiate module cfp.hotkeys due to:
> Error: [$injector:nomod] Module 'cfp.hotkeys' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by benmarch** [comment]
Thanks, @stodolos! Just fixed it.

**Comment by stodolos** [comment]
sweet!  Thanks!
