### ISSUE TITLE
Prevent scrolling true,Backdrop

### ISSUE THREAD

**Issue by amanraghubansi** [benmarch/angular-ui-tour#41]
1.On start i am making prevent scrolling true but when coming to same step, after going forward and back by 1 step, prevent scrolling was not working.
2. backdrop is not covering entire page..it is covering only current viewport...
pasting below code for above 2 points:

``` html
<div tour-step tour-step-title="Intro to payments"  tour-step-order="5" tour-step-placement="bottom" tour-step-scroll-into-view="true" tour-step-backdrop="true" tour-step-prevent-scrolling="true" >
```

**Comment by benmarch** [comment]
Hey @amanraghubansi, I copied your tour step into my testing environment and it appears to work as expected. Are you seeing any errors in the console? Also, you can remove `tour-step-scroll-into-view="true"` since that is the default setting.

**Comment by amanraghubansi** [comment]
In my environment,page is divided into 2 portions one is aside and other is page content where aside is on full page width and page content is displayed as per tabs in the aside menu.PopUp is positioning itself in arbitrary manner.

**Comment by amanraghubansi** [comment]
Hi,
We are using it in mobile also.Can you please put the light on it as in responsive things are going really bad.

**Comment by benmarch** [comment]
Hi @amanraghubansi, can you upload some screenshots or screencasts of the issues? Also, do you have a public domain that this is hosted on so i can take a look? With respect to mobile, this library only supports what Angular UI Popovers support, and they do have a [disclaimer](https://angular-ui.github.io/bootstrap/#/popover) about it.

**Comment by benmarch** [comment]
By the way, if you don't absolutely need preventScrolling then it is best not to use it. In many cases removing it solves the problem.

**Comment by amanraghubansi** [comment]
Hi @benmarch ,
public hosted url is  :  http://d9vzscd3uez7f.cloudfront.net/index.html#/
use account ID: 1001760
username : umraouser@gmail.com
password : afda
...Please make note of data as i will delete user login info. very soon.....
In left panel tooltips,I have used the fixed position,,,because scroll into view is a hair pulling thing for me to position tooltip in mobile and desktop view...mobile view really difficult to take care...so i have used css fixed values to take care....but for short length phones e:g Iphone4 causing problems when last step of thanks tour is shown....
Just try to emulate browser in iphone4..click on hamberger icon....click on take a tour...then click on the redemption....complete tour....don't exit tour at last step....you will get to know of issue, where you will not be able to scroll in view and popup will be out of screen :( :(....
If you can help me with left side issues within 1 day...that will be of great help as need to release code..

**Comment by benmarch** [comment]
Thanks, @amanraghubansi, I have saved the user data if you want to delete it. I will try to take a look later today.

**Comment by benmarch** [comment]
Hey @amanraghubansi I see the issue:
![screen shot 2016-04-14 at 5 31 18 pm](https://cloud.githubusercontent.com/assets/1646126/14544385/cde68142-0266-11e6-8d28-5a0f4f7cbd30.png)

I only have one suggestion, but keep in mind that this library does not _fully_ support mobile due to the nature of popovers. Try setting the placement to "top" since it looks like it will fit better above the link than below it. I also noticed that you are setting the top and left positions explicitly for that step because it looks like the coordinates are not calculated correctly. I will look into why it is not working as expected (I thought I had fixed that before releasing the latest version) but in the meantime it looks like setting top to 135px works well.

**Comment by amanraghubansi** [comment]
Hi,
Do you came to know about reason why coordinates was not getting calculated correctly for top property of the popup because items in left panel are getting increased in next release and i have to take care of it.

**Comment by benmarch** [comment]
It appears that it is calculating the offset based on the document instead of the viewport. I am still looking into why this is happening since it is supposed to use the viewport offset when "fixed=true".

**Comment by benmarch** [comment]
Hey @amanraghubansi, I have a fix for the incorrect coordinate calculation but it introduces a new dependency on [Tether](http://github.hubspot.com/tether/). Instead of trying to implement my own position library, I am just going to use that. I am going to release a patch tomorrow with some other bug fixes, and then I will release a pre-release with the Tether changes so that you can test them out. Will you be able to pull it into your build and test it sometime tomorrow or the next day?

**Comment by amanraghubansi** [comment]
Hi,
Yeah sure, I will be able to do test as soon as it is available....Correct position will be calculated for cases where we have fixed position or scroll into view for left panel in my case too??

**Comment by benmarch** [comment]
Yes, that is what I am hoping. It appears to work on my machine, but I want to make sure it works in your app as well. I will update you with the details as soon as they are available. Thanks!

**Comment by benmarch** [comment]
Ok I have created a branch with the changes here: https://github.com/benmarch/angular-ui-tour/tree/41-fixed-element-position

Please install that version and let me know if it works for you. I was having mixed results locally, but if it works for you I will keep it for now. Ultimately, I would like to have a simpler solution, but this should be ok for now. Please note the added dependency on Tether.

**Comment by amanraghubansi** [comment]
Hi @benmarch ,
I have tried it,but it does not work in my case.PFA screen shot.
![demoimage1](https://cloud.githubusercontent.com/assets/9050585/14712850/6fa1144e-07fc-11e6-9b35-847fefc5b0a1.png)

Points to consider:
1. not working with tour step marked as fixed.
2. In side bar tour elements,if elements is not marked with tour-step-fixed='true' as doing in step 1.....Tour highlighting of element is not correct and position is don't know how is getting calculated.

PFA screenshot for 2nd case.
![screen shot 2016-04-21 at 8 12 44 pm](https://cloud.githubusercontent.com/assets/9050585/14713143/8eed7c60-07fd-11e6-9249-4be458932574.png)

**Comment by benmarch** [comment]
Hey @amanraghubansi, looks like it's back to the drawing board. I have another idea how to handle this, but it might take some time. It looks like the logic for the highlight window is pretty good (although it could use some work when the window is resized) so I will look into abstracting that so I can use it for the popup placement as well. Sorry for the inconvenience.

**Comment by amanraghubansi** [comment]
HI @benmarch 
Can you do one thing :  If you can provide some config parameter to add some class or add active class to element on which tooltip is currently being shown,,,I can temporarily make an solution for my environment..and later we can opt for correct solution. :)

**Comment by benmarch** [comment]
Yep, I actually just closed out that issue with 0.5.4. Whenever a step it active, it adds the "ui-tour-active-step" class to the target element (the element on which the step is defined).

FYI, I will be traveling for work all next week so this fix might take longer than I was hoping.

**Comment by benmarch** [comment]
Hey @amanraghubansi, can you try this again with Angular Bootstrap 2.x and Angular UI Tour 0.6.0?

**Comment by amanraghubansi** [comment]
Hi,
I will try but it will take some time as i am occupied with some other tasks.

**Comment by rafialikhan** [comment]
Any luck on this?

**Comment by benmarch** [comment]
Made progress on this, although I'm not entirely sure if it is resolved. I have switched to using Tether in version 0.8.0, and I believe this will solve most of the issues you are seeing here. I am going to release a few patches in the coming weeks that will enhance the positioning further, including constrains on the viewport so that the popup is always in view. Thank you for you patience.

**Comment by amanraghubansi** [comment]
Hi benmarch, 
This time i am getting problems when trying to add tour over elements  present in $uibmodal window of angular bootstrap.If you can check with this, that will be great help or help me with source code data points so that i can contribute to make it better

**Comment by benmarch** [comment]
Hey @amanraghubansi,

That might be an issue with the z-index of the backdrop. Can you try setting the `tour-backdrop-z-index` property to something higher than that of the modal? Try `1500` to start.

Thanks,
Ben

**Comment by benmarch** [comment]
Hey @amanraghubansi, any updates?

**Comment by benmarch** [comment]
Closing issue. Please reopen if it is still present in the latest version.
