### ISSUE TITLE
multiple tour instances issue

### ISSUE THREAD

**Issue by amanraghubansi** [benmarch/angular-ui-tour#44]
Hi,
How I will be getting the multiple tour instances object...as tour object is added to scope by API....how to get tour obj of in case of multiple tours...???

**Comment by benmarch** [comment]
In that case you would use the uiTourService and use one of the methods in the documentation to get the tour that you want. You will probably use `uiTourService.getTourByName(<name>);` which will return a reference to the tour instance.

**Comment by benmarch** [comment]
Hey @amanraghubansi, did my suggestion solve your issue?

**Comment by amanraghubansi** [comment]
Hi,
I have not tried for multiple tour case since then,But once i try will let you know. :)

**Comment by benmarch** [comment]
Hey @amanraghubansi, any update on this?

**Comment by amanraghubansi** [comment]
Hi,
As application  was SPA so instead of using multiple tours i have used single tour only and have started tour at given step as per my requirement.

**Comment by Disane87** [comment]
@amanraghubansi How did you achived this? I have a SPA as well and I want to initiate a tour on my main view and the steps in other (child) views.

**Comment by amanraghubansi** [comment]
@Disane87 In main view you will start tour at given point using api functions, then in sibling or child state, while transition i pass state parameter and then in new state controller i use like : 
uiTourService.getTour().startAt('tourStepNameInSiblingOrChildState');

**Comment by Disane87** [comment]
perfect! I gonna check that :)

Mit freundlichen Grüssen / Kind regards
Marco Franke

** Von meinem iPhone gesendet

**Comment by benmarch** [comment]
This seems to be resolved. If not, let me know and I will reopen it.
