### ISSUE TITLE
Bump version on npm

### ISSUE THREAD

**Issue by thekip** [benmarch/angular-ui-tour#45]
Currently in NPM has a diffrence between versions in the repository and in NPM. 

In repository in Bower.json version is 0.5.3
In NPM in Bower.json version is 0.4.0

So npm package is outdated and must be updated.

**Comment by benmarch** [comment]
I wish I could, but @findify uploaded an out-dated fork of this project before I could. 

@findify, please transfer ownership back to me so that I can keep it up-to-date. Next time just ask me to upload it instead of doing it yourself.

**Comment by wojciak** [comment]
@benmarch transfered - sorry for the inconvenience, I've forgot to add @findify to the package name :/

**Comment by benmarch** [comment]
Thank you, @wojciak, no problem.

@thekip, NPM now contains the latest version. Please note that older versions in NPM are not the same as the Bower versions as @findify made some modifications before publishing.
