### ISSUE TITLE
Backdrop blinked between two steps with tour-step-backdrop=true

### ISSUE THREAD

**Issue by nilagor** [benmarch/angular-ui-tour#46]
When I switch between the two steps with `tour-step-backdrop=true` I see backdrop flashes for a split second - is lost and then reappears. 
I record little demo, you can see it here - http://take.ms/iDuLK.

Can you fix this? Or maybe i do something wrong?

**Comment by benmarch** [comment]
Hey @nilagor that is really interesting. Thank you for the screencast, I believe that I can fix that. For my knowledge, are you implementing anything onNext/onPrev that might delay the step loading? I will try to reproduce your environment as closely as possible.

**Comment by nilagor** [comment]
@benmarch thanx for fast answer!
I didn't make anything that could affect the switching speed. Custom popup template could hardly affect it. 
If you have a problem call me - I will try to make a simple working demo

**Comment by benmarch** [comment]
Ok cool, I actually have noticed short delays with custom templates, but I think I can set up the backdrop so it knows if the next step also has a backdrop (in which case, just move it instead of regenerating it).

**Comment by benmarch** [comment]
Version 0.5.4 includes these changes.
