### ISSUE TITLE
uib-popover-popup attribute missing from tour step template

### ISSUE THREAD

**Issue by nathancoates** [benmarch/angular-ui-tour#48]
Would you be able to add this in? Without it, the arrow on the popups don't respect the placement setting. Thanks!

**Comment by benmarch** [comment]
Hey @nathancoates, I'm not quite sure what you mean. Can you provide screenshots showing the issue that you are experiencing? I don't see any documentation for that attribute on the [Angular UI website](https://angular-ui.github.io/bootstrap/#/popover), can you point me to some information about it?

Also, what version of this library are you using, and how did you install it? There was an issue with NPM recently so I want to make sure that you are using a valid version.

Thanks,
Ben

**Comment by nathancoates** [comment]
Hi Ben. Thanks for the quick reply. I'm using 0.5.3. Here's a screenshot of the ui-bootstrap docs. 

<img width="1198" alt="screen shot 2016-04-20 at 11 46 50 am" src="https://cloud.githubusercontent.com/assets/3833944/14681186/16b882fe-06ee-11e6-8834-f6460814a995.png">

As you can see, when the popover is positioned bottom-right, an inline stylesheet (which I assume is loaded in by ui-bootstrap) is using the uib-popover-popup attribute to override the styling of where the pointer goes, in this case, it pushes it to the right. In the tour, even when I set the position of a tour step to bottom-right, the pointer stays centered since there is no uib-popover-popup attribute. I can obviously override this in a style sheet, but I just wanted to bring it to your attention.

Hope that all makes sense.

**Comment by benmarch** [comment]
Ah ok I see what you mean. It's really unfortunate that they did it that way, they really should have used a class instead of the directive attribute. I think I can add that safely; I will queue it up for tonight's release.

Thanks,
Ben

**Comment by benmarch** [comment]
Version 0.5.4 includes these changes.
