### ISSUE TITLE
$uibPosition.viewportOffset is not a function error

### ISSUE THREAD

**Issue by burakkilic** [benmarch/angular-ui-tour#49]
Hi;

I am getting $uibPosition.viewportOffset is not a function error if I add backdrop to a step. 

     <div class="col-lg-3 col-lg-offset-1 col-md-4 col-sm-4 col-xs-12" tour-step tour-step-title="Main Menu" tour-step-content="Navigate the site using this menu." tour-step-order="0" tour-step-placement="top" tour-step-backdrop="true">

What is wrong?

**Comment by burakkilic** [comment]
It was about bootstrap-ui version. Sorry about that. Closing...

**Comment by novakben** [comment]
I'm facing this exact same issue now:
```
angular.js:13424 TypeError: $uibPosition.viewportOffset is not a function
    at Object.service.createForElement (angular-ui-tour.js:92)
    at angular-ui-tour.js:483
    at processQueue (angular.js:15757)
    at angular.js:15773
    at Scope.$eval (angular.js:17025)
    at Scope.$digest (angular.js:16841)
    at Scope.$apply (angular.js:17133)
    at done (angular.js:11454)
    at completeRequest (angular.js:11652)
    at XMLHttpRequest.requestLoaded (angular.js:11593)
```

But only when adding the ```tour-step-backdrop="true"``` directive.
Any suggestions?

**Comment by benmarch** [comment]
Hey @novakben, what versions of Angular, Angular Bootstrap, and Angular UI Tour are you using?

**Comment by novakben** [comment]
Hey @benmarch :) 
```
    "angular-bootstrap": "~0.14.3",
    "angular": "~1.5.3",
    "angular-ui-router-title": "~0",
    "angular-ui-tour": "^0.5.5"
    "angular-animate": "~1.5.3",
    "angular-cookies": "~1.5.3",
    "angular-sanitize": "~1.5.3",
    "angular-messages": "~1.5.3",
    "angular-aria": "~1.5.3",
    "angular-resource": "~1.5.3",
    "angular-ui-router": "~0.2.15",
```
and resolutions:
```
  "resolutions": {
    "angular": "~1.5.3"
  }
```
Cheers!

**Comment by benmarch** [comment]
Ah ok, it's because of the angular-bootstrap version. It looks like I made a mistake with the allowed version range (1.0.0 should be the lowest allowed version.) If you can upgrade to angular-bootstrap 1.x.x it will work, otherwise you will have to wait for #66 because there are other issues with angular-bootstrap versions. Sorry for the inconvenience, I am working as quickly as possible to resolve all of these issues.
