### ISSUE TITLE
Ability to remove Pause button?

### ISSUE THREAD

**Issue by burakkilic** [benmarch/angular-ui-tour#50]
Hello;

How we can remove pause button?

**Comment by themainframe** [comment]
Override the template for the popup with the `templateUrl` config option in a `config` block, or you can also use an attribute on the `ui-tour` element (`ui-tour-template-url="'some-other-template.html'"`).

**Comment by benmarch** [comment]
Hey @burakkilic, @themainframe's answer is correct.

Thanks, @themainframe!!

**Comment by burakkilic** [comment]
Thank you @themainframe ! One more question: Where should I place this html file? Should it be in $templateCache?

**Comment by benmarch** [comment]
Hey @burakkilic, you can provide any URL to the template file, and it will look to the $templateCache first to see if it exists there.

**Comment by burakkilic** [comment]
Thank you very much!

**Comment by coskuntekin** [comment]
need to update

`data-tour-step-template-url="'tour-step-other-template.html'"`
