### ISSUE TITLE
removeStep doesn't verify if the step is actually in the list.

### ISSUE THREAD

**Issue by jgutix** [benmarch/angular-ui-tour#51]
`removeStep` always removes at least one step, no matter if the step isn't actually in the list, check the line: https://github.com/benmarch/angular-ui-tour/blob/master/app/tour-controller.js#L227

That method should be changed for:
```
self.removeStep = function (step) {
    var index = stepList.indexOf(step);
    if(index !== -1){
        stepList.splice(index, 1);
        self.emit('stepRemoved', step);
    }

};
```

**Comment by benmarch** [comment]
Hey @jgutix, I am so sorry for the long delay, I thought I had responded to this earlier. Thank you for bringing this to my attention, I will fix it in the next release.
