### ISSUE TITLE
Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by sergeykolesnikov** [benmarch/angular-ui-tour#54]
Hello, I have a problem, when steps on different pages have a backdrop, I have this error on change steps. For example, I have pages "/index" with step "1" and "/test" with step "2", I set next-path and next-step, it redirects me where I want, and as i see, it finds step, but then error, and backdrop not change, it holds position like at previous page. If I disable backdrop for this steps, all ok.

Error in this row, just after "getStep()"
Seems like it can't getStep(), but I don't know why... as I said before, it shows right step on next/prev page..

```
//if the next/prev step does not have a backdrop, hide it
if (getCurrentStep().config('backdrop') && !actionMap[goTo].getStep().config('backdrop')) {
       uiTourBackdrop.hide();
}
```

P.S. sorry for my english, not my native language )

**Comment by sergeykolesnikov** [comment]
Update: this error, when clicking "Next" and go on next page, disappeared, but I changed nothing.. But if I press "Prev" and go on previous page, it shows this error again

**Comment by benmarch** [comment]
Hey @sergeykolesnikov, I was unable to reproduce the error that you reported, but I was able to reproduce the backdrop persisting in the wrong place on the next page. Can you share the tour config, as well as the config for each step involved so I can use your setup to try to reproduce the error?

Thanks,
Ben

**Comment by sergeykolesnikov** [comment]
Thanks for reply @benmarch !

But problem is that even backdrop wrong placement  caused by that error "Cannot read property 'config' of undefined".. as I said in previous comment, this error disappeared for button "Next", and backdrop shows almost right, but if I click "Prev", I have an error and backdrop shows in a strange way.

This is how it shows while we on the first page
![sidebar](https://cloud.githubusercontent.com/assets/17004512/15207547/9a5815c8-182f-11e6-8ef2-a038b09ef3d2.png)

This is after we click "Prev" button and an error
![sidebarwrong](https://cloud.githubusercontent.com/assets/17004512/15207558/ae8fcacc-182f-11e6-9e58-26f2dcf990e9.png)

This is how it shows on the next page
![faq](https://cloud.githubusercontent.com/assets/17004512/15207559/b8ba89f6-182f-11e6-8507-2e5e570a4a06.png)

You asked me to share this?

This is my tour config:

`TourConfigProvider.set('scrollOffset', 300);
TourConfigProvider.set('backdrop', true);
TourConfigProvider.set('useHotkeys', true);
TourConfigProvider.set('appendToBody', true);`

These are steps with backdrop wrong placement (steps on which it redirects us)

index.html

`<div class="col-md-4 col-sm-12 col-md-pull-8 sidebar" tour-step="step-three" tour-step-next-path="faq" tour-step-next-step="step-four" tour-step-title="Recently won" tour-step-content="Check what other people have won recently" tour-step-order="3" tour-step-placement="top"></div>`

faq.html
`<h2 class="text-center" tour-step="step-four" tour-step-prev-path="/" tour-step-prev-step="step-three" tour-step-title="RECENTLY_WON" tour-step-content="Check what other people have won recently" tour-step-order="4" tour-step-placement="bottom">Frequently Asked Questions</h2>`

**Comment by benmarch** [comment]
Hey @sergeykolesnikov, sorry I did not respond earlier. Could you provide the versions of Angular, Angular UI Bootstrap, and Angular UI Tour? I am still unable to reproduce the error.

Thanks,
Ben

**Comment by sergeykolesnikov** [comment]
@benmarch No problem )

Angular 1.5.3
Angular UI Bootstrap 1.3.1
Angular UI Tour 0.5.4

**Comment by sergeykolesnikov** [comment]
Hi, @benmarch 

I saw it today: 

It's in function goTo()

1) `if (getCurrentStep().config('backdrop') && !actionMap[goTo].getStep().config('backdrop')) {
         uiTourBackdrop.hide();
}`

It works when steps on the same page, but actionMap[goTo].getStep() returns 'undefined' if a redirect occured.

And I wrote "console.log(actionMap[goTo].getStep())" in your Demo Tour. After a redirect, it shows last step on first page, how it works?
![2016-05-17 15 58 26](https://cloud.githubusercontent.com/assets/17004512/15324205/2cd64e5c-1c4e-11e6-9f3a-1e6020f8b374.png)
![2016-05-17 15 57 20](https://cloud.githubusercontent.com/assets/17004512/15324218/3bdf3e4a-1c4e-11e6-90cc-b04be73d94c4.png)

I can remove these code, and then it works almost fine,but it's a bad solution.. 

2) I have 3 pages. For example I have no problem with 1), but one problem remains. I can go from 1 to 2 page, from 2 to 3, from 3 to 2, and it's ok, but when I go from 2 to 1, something is going wrong, I have no errors, but it doesn't update backdrop, I found one, but not the main reason. 

`if (!currentStep[actionMap[goTo].navCheck] || currentStep[actionMap[goTo].navCheck] !== getCurrentStep().stepId) {
                        setCurrentStep(actionMap[goTo].getStep());
                        self.emit('stepChanged', getCurrentStep());
                    }`

So, as I understand this code must be executed only for steps on the same page, for this reason it looks at Id of the next\prev page and Id of current page (after redirect), but I saw that when I go from 2 to 1 page, it take Id of the prev page, and Id of the current page(before redirect), so they are not equal, and it executes the code above.

Do you have some ideas, why it works this way?
Thanks!

**Comment by sergeykolesnikov** [comment]
Hello, @benmarch! 
I found out what's the problem with backdrop wrong placement, it's caused by slow page loading, when I put timeout in function
`$timeout(function () {
                        uiTourBackdrop.createForElement(step.element, step.config('preventScrolling'), step.config('fixed'));
                    }, 80);`
it works fine, but I'll look for better solution. I think it must be possible to know whether it loaded all content or not, then calculate and show backdrop.

**Comment by benmarch** [comment]
Hey @sergeykolesnikov, sorry for not responding for a couple days! I have created a new branch with some changes that should fix this issue. Try installing branch 54-error-on-navigate, and let me know if it resolves your issues (should address both the errors and the backdrop issue).

Thanks,
Ben

**Comment by sergeykolesnikov** [comment]
Hello, @benmarch, yes, it fixed error on redirect, thanks! But, unfortunatly, problem with backdrop early calculating still remains.

And one more thing about backdrop, I have absolute footer and body not always 100% height of page, and cause of that backdrop not cover all page, I found a solution, it works for my site.. I think it must work everywhere, but when I wrote this code in your demo in browser, it wasn't working as expected, maybe because it was in browser.

This code in the 'service.createForElement'
`var documentHeight = document.documentElement.offsetHeight;`

and in the 'viewWindow.bottom.css' calculate height with this
`height: documentHeight - (position.top + position.height) + 'px',`

**Comment by benmarch** [comment]
Hi @sergeykolesnikov, I have noticed the issue with the backdrop not covering the entire page also, but I am no longer able to recreate the delayed position calculation. I will continue to poke at it and see if I can fix that, or at least recreate it locally.

**Comment by sergeykolesnikov** [comment]
@benmarch okay, thanks! And if I'll find something I will let you know
