### ISSUE TITLE
Tour never ends

### ISSUE THREAD

**Issue by burakkilic** [benmarch/angular-ui-tour#55]
Hi;

I have a tour with 14 steps. When the last step comes, next button is not hidden. Where am I wrong?

**Comment by benmarch** [comment]
Hi @burakkilic, can you paste in the markup for your last step, and all of the tour config?

**Comment by burakkilic** [comment]
<a class="btn btn-danger pull-left" ng-click="startTour()" tour-step tour-step-title="{{'Take Tour?' | translate}}" tour-step-appendToBody="true" tour-step-content="{{'You can watch this tour at any time by pressing this button.'}}" tour-step-order="15" tour-step-placement="bottom">{{'Take Tour' | translate}}</a>

I don't have special config.

**Comment by benmarch** [comment]
Interesting, are there any console errors?

**Comment by burakkilic** [comment]
No. But the other thing is, from step 3 to 14, it is included in a partial (sidebar.html) but they are shown successfully.

**Comment by benmarch** [comment]
Sorry for all the questions.... does the popup on the 14th step have a "Next" button?

**Comment by burakkilic** [comment]
Yes. And the template is:

    <script type="text/ng-template" id="test.html">
    <div>
        <div class="popover-content tour-step-content" ng-bind-html="tourStep.trustedContent"></div>
        <div class="popover-navigation tour-step-navigation">
            <div class="btn-group">
                <button class="btn btn-sm btn-default" ng-if="tourStep.isPrev" ng-click="tour.prev()">&laquo; {{'Prev' | translate}}</button>
                <button class="btn btn-sm btn-default" ng-if="tourStep.isNext" ng-click="tour.next()">{{'Next' | translate}} &raquo;</button>
            </div>
            <button class="btn btn-sm btn-default" data-role="end" ng-click="tour.end()">{{'End tour' | translate}}</button>
        </div>
    </div>
</script>

**Comment by benmarch** [comment]
Ohh damn are you using the latest? 0.5.4? I may have made a breaking change without realizing it. Try changing `ng-if="tourStep.isPrev"` to `ng-if="tourStep.isPrev()"` and do the same with isNext().

**Comment by burakkilic** [comment]
Yes it is 0.5.4 but when I did this, no button is shown.

**Comment by benmarch** [comment]
Ok, I am thinking that the last step is not added properly to the tour for some reason. You can confirm that by looking at `tour._getSteps()`. Most likely it just isn't available to the tour when the step is supposed to be shown. Just make sure that the step is defined on the page before the 14th popup is shown, and that it is within the scope of the tour. Also, change `tour-step-appendToBody` to `tour-step-append-to-body` to see if that makes any difference. Sorry for the speculation, it is a bit difficult to debug without seeing the entire app. If you have a way for me to take a look at the whole app in order to debug I would be happy to do so.

**Comment by benmarch** [comment]
Hey @burakkilic, any update on this?

**Comment by akholodenko** [comment]
changing` ng-if="tourStep.isPrev"` to `ng-if="tourStep.isPrev()"` fixed the issue I was having with proper step buttons not being shown when hitting the last step.

**Comment by benmarch** [comment]
This seems to be resolved. If not, please let me know and I will reopen it.

**Comment by elhampour** [comment]
your source code in demo tour web site, is not based on your latest changes, please change it , so others done have problems like me. for example this line of code 

tourStep.isPrev

tnx a alot.
