### ISSUE TITLE
Left blackout box is not at left:0 when using 3 column layout

### ISSUE THREAD

**Issue by joecoolish** [benmarch/angular-ui-tour#56]
I manually had to add the `left:0` to the `viewWindow.left.css` object within the `createForElement` function of the uiTourBackdrop service in order for it to be aligned to the left.  My layout is such that it was pushing the left blackout all the way to the right when `left:auto` was used.  I had to explicitly set `left:0` for it to come into view.

**Comment by benmarch** [comment]
Yeah there are multiple issues with the way that both the backdrop and the steps position themselves. I think I am going to have to use a better positioning library than $uibPosition, and I will probably forgo Angular UI's tooltips and just build my own, simpler implementation. They unfortunately don't offer the hooks necessary to create a library like this one, so I have had to hack at it a bit and now it has become a bit of a mess. I will let you know when I make some progress on it.

**Comment by joecoolish** [comment]
Sounds good.  I'm making some changes to add animating the backdrop in and out and between steps.  I'll keep you posted!

I actually wrote a tour framework several years ago, and instead of re-writing it to fit angular, I'm liking yours!  I hope you don't mind the pull requests :)

p.s.  What are your thoughts on TypeScript?

**Comment by benmarch** [comment]
That's awesome! Please keep the PRs coming, I'm finding it harder to free up time to work on this so I will gladly accept contributions!

I have mixed feelings about TypeScript. I consider myself a bit of a Crockford fundamentalist when it comes to JavaScript, so static typing seems like it is the wrong direction for the language; however, coming from a C and Java background I recognize the benefits in compile-time checking. I think that the way the Angular 2 team has used TypeScript with its DI system is fantastic (using the type to determine which dependency to inject) and it will make it easier for developers coming from a Java/Spring background. I haven't really gotten my hands dirty in it though, so my thoughts about it are fairly trivial. Were you thinking that this library could benefit from it? I was planning on porting to ES6+ as soon as I find the time, but if you can convince me to go with TS then I will definitely consider that instead.

**Comment by benmarch** [comment]
Yes, I do really like the interfaces, and TS classes are superior to ES6 classes at the moment (access modifiers, for example). I wrote [another library](https://github.com/benmarch/decorangles) that provides a small set of decorators for Angular 1.x and ES6+, which could also be useful with TS. I would definitely like to see what you come up with!

**Comment by benmarch** [comment]
Closing issue. Please reopen if it is still present in the latest version.
