### ISSUE TITLE
Remove previous step when using startAt()

### ISSUE THREAD

**Issue by snowyaaron** [benmarch/angular-ui-tour#58]
So I am not sure if this is an unintended consequence or maybe I am using it wrong however if I want to startAt(200) lets say the previous button still comes up and takes me back to 199. I want to be able to startAt() and only move forwards.

**Comment by benmarch** [comment]
Hey @snowyaaron, unfortunately, that is the expected behavior of startAt(). It was originally intended to be a way to resume a paused tour, or skip to a specific step. In order to achieve your desired behavior, you will probably have to create [multiple tours](https://github.com/benmarch/angular-ui-tour#multiple-tours), or use [`tour-step-enabled="{{somethingFalsey}}"`](https://github.com/benmarch/angular-ui-tour#additional-options) on previous steps when you skip them.

**Comment by snowyaaron** [comment]
Would there be a way to possibly load in a new template without the Previous Button? Or can you only load in one template?

**Comment by benmarch** [comment]
Absolutely, you can even have conditional templates (untested, but theoretically it should work). Just set the `tour-step-template-url` attribute which takes an Angular Expression that evaluates to a string. The expression can call a function on the scope that determines the template based on whether or not you skipped the previous steps (up to you to create the logic). Try it out and let me know if you have any questions.

**Comment by snowyaaron** [comment]
Okay but when I do this, the template for the tour does not show up:

Body level:
ui-tour-template-url="'folder/mainTemplate.html'">

Inside a Div in the Body:
ng-click="tour.startAt('200')"
tour-step-templateUrl="folder/test.html"

**Comment by benmarch** [comment]
I'm not sure if this is a copy error, but `tour-step-templateUrl` should be `tour-step-template-url` and `folder/test.html` needs single quotes inside the double quotes.

What do you mean by the template for the tour does not show up? Are the templates loading into the browser properly? Any errors in the console?

**Comment by stratdaz** [comment]
My page has a tabset, with specific tour steps belong to specific tabs and I was hoping to modify the tour (disable and enabled steps) based on the selected tab. 

I tried expressions in "tour-step-enabled" but seems this doesn't work dynamically. 

_tour-step-enabled="tabState == 1"_

Thinking my best chance is to explicitly add/remove steps on a tab click event.

Any suggestions appreciated.

Thanks

**Comment by benmarch** [comment]
Hi @stratdaz, that should work as expected as long as `tabState` is available on the step's enclosing scope. Timing might be an issue; the expression is evaluated on step navigation, so it is possible that the state is not 1 at that time. Although you could create multiple tours, I don't really recommend it for this use case.

If you continue to experience issues, please feel free to open a new issue.

**Comment by stratdaz** [comment]
Thanks for your reply.

This is closer ...

_tour-step-enabled="{{tabState == 1}}"_

and now addStep and removeStep run as expected here ...

_enabledWatch = attrs.$observe(TourHelpers.getAttrName('enabled'), function (isEnabled) {
    step.enabled = isEnabled !== 'false';
    if (step.enabled) {
        ctrl.addStep(step);
    } else {
        ctrl.removeStep(step);
    }
});_

Still have an issue though. I have a total of 6 steps in my tour and I have moved one step to a second tab (tabState 1) and that's the one I want to disable if the user is on the first tab (tabState 0).

After the code above runs the internal "stepList" array is indeed now 5 but when I step through the tour the "stepList" referenced has all 6 steps and the step I'm trying to hide is still part of the tour. Pretty sure I'm not doing anything unusual but it's almost like I have multiple tours with individual step lists?

**Comment by stratdaz** [comment]
PS, if I set this ...

_tour-step-enabled="false"_

then the tour works as expected, correctly hiding the step. Looks like I'm doing something wrong so will keep digging.

**Comment by stratdaz** [comment]
Follow up ...

I think you're right about the timing thing and "enableWatch" and "orderWatch" are stepping on each other's feet.

If I disable the "orderWatch" block of code then it works ok.
