### ISSUE TITLE
How to open tour on page load?

### ISSUE THREAD

**Issue by nasy** [benmarch/angular-ui-tour#6]
Hi,

First of all thank you for this project, it is very useful. 

However I need to launch the tour based on a controller variable received from the server. 

Something like this:

$scope.loadSettings = function() {

   if($scope.launch_tour == true){
      tour.restart(true);
   }
};

Tried different things but no luck so far. Any ideas?

**Comment by nasy** [comment]
Hey guys, still struggling to find a solution for this. Any suggestions?

**Comment by benmarch** [comment]
Sorry for the delay, I just got back from a long vacation. Looks like you are using the API from Bootstrap Tour, try using `tour.start()` instead. The tour object is added to the scope of the element that declares it, but you can also set an onReady callback and capture the tour object there (see #1).

**Comment by nasy** [comment]
Hope you enjoyed the vacation. :) I finally changed the design and now i am using a button to trigger the start event. Thanks anyway.

**Comment by benmarch** [comment]
Thanks @nasy! I'm going to close this one, but I do have a plan to create a service that will expose all available tours to DI. So if you decide to change the design back you will have the option to handle that behavior outside of a controller.
