### ISSUE TITLE
Angular 2 port?

### ISSUE THREAD

**Issue by jFensch** [benmarch/angular-ui-tour#60]
Have you considered porting this Angular 2?

**Comment by benmarch** [comment]
Hey @jFensch, I just noticed that I never responded to this, sorry about that. The first step here would be porting to ESNext or TypeScript. After that, I would have to see how to support both ng1 and ng2 using the same codebase. I'm sure it is possible, I'm just not familiar with it yet.

**Comment by isaacplmann** [comment]
It seems like there hasn't been much traction in this direction.  I'm working on an angular2 version of the tour that draws ideas from this project.  I'll update this issue when it is ready for public consumption.  I'd ordinarily submit a PR to this library, but the codebase is different enough that I think it would be difficult to live along side an angular 1.x library.

**Comment by isaacplmann** [comment]
Check out [ng2-tour](https://isaacplmann.github.io/ng2-tour/).  It's pretty bare bones right now compared to this library, but it has the basic features and is entirely written in Angular 2.

**Comment by benmarch** [comment]
Hey @isaacplmann that looks awesome! Well done! I'm going to close this issue but please keep me updated on progress.
