### ISSUE TITLE
Scrolling doesn't work

### ISSUE THREAD

**Issue by schuesslerf** [benmarch/angular-ui-tour#62]
just implemented Angular Ui Tour (https://github.com/benmarch/angular-ui-tour) on my site, everything seems to work, except scrolling to the opened dialog.

I created and started the tour like that:

```
uiTourService.createDetachedTour('myTour');
this._uiTourService.getTourByName('myTour').start();
```
And the tour steps are defined like so:

```
<div tour-step tour-step-title="Main Menu" tour-step-content="Navigate the site using this menu."
     tour-step-order="0" tour-step-placement="bottom-left" tour-step-belongs-to="myTour"></div>
<p tour-step tour-step-title="second step" tour-step-content="this is the second step"
   tour-step-order="1" tour-step-placement="bottom" tour-step-belongs-to="myTour"></p>
```
Everything is shown correctly, i also managed to use my keyboard to navigate (arrow keys), setting useHotkeys to true. But the scrolling thing won't work, even if I try to set scrollIntoView to true manually.

Do you see anything wrong there or why doesn't it work?

**Comment by benmarch** [comment]
Hey @schuesslerf, thank you for including the code snippets. I don't see anything glaring that would cause it not to work, are there any errors in the console? It sounds to me like the angular smooth scroll dependency is not included or not working, but I would expect an error in that case. What versions of angular and angular ui are you using? Sometimes they change something on me and I need to update.

**Comment by schuesslerf** [comment]
There are no errors showing in console, unfortunatelly... I'm using Angular 1.5.7 and what you mean with angular ui? I'm using angular ui bootstrap in version 1.3.3 and angular ui tour with version 0.5.4, ngSmoothScroll is on version 2.0.0... I actually tried to match the dependencies you determined in your bower.json (I installed it with npm but made sure to have all dependencies installed). But I still have no idea, what the problem could be...

**Comment by benmarch** [comment]
Sorry for the ambiguity, I meant angular ui bootstrap. I updated my local test environment to reflect the versions that you are using, but I am unable to reproduce the issue. I'm a little stumped as to what could cause this behavior without error. I can offer a few suggestions, but I doubt any of them are the case: Do you have any custom scrolling behavior in your app? Did you set the popupDelay to 0? Is there possibly a syntax error in the markup?

If I think of anything else I will report back, let me know if you are able to resolve it. We can leave this open in case others experience the same problem.

**Comment by schuesslerf** [comment]
Thanks for the suggestions, but non of them are the case.. And no, I couldn't find any syntax error....

Yeah, I will get back to you if I find any problem I caused or if I solved it.

**Comment by schuesslerf** [comment]
Hello again, I'm happy to tell you that I found out why its not working: I used the minified version of ng-smooth-scroll and not the "normal" one. Including the normal one, everything now works as it should. Propably add this hint, so it's clear to use the normal version.

**Comment by benmarch** [comment]
Hey @schuesslerf, thank you for figuring this out! It looks like this is a problem with ngSmoothScroll: https://github.com/d-oliveros/ngSmoothScroll/issues/57

I will make a note in the README about it, sorry for the inconvenience.
