### ISSUE TITLE
angular and angular-bootstrap version :(

### ISSUE THREAD

**Issue by aashhissh** [benmarch/angular-ui-tour#63]
Hey, i am trying to use your library but while installing it says below 
Unable to find a suitable version for angular, please choose one by typing one of the numbers below:
    1) angular#~1.2.23 which resolved to 1.2.29 and is required by angular-bootstrap-tour#0.3.4
    2) angular#>=1 <1.3.0 which resolved to 1.2.29 and is required by angular-bootstrap#0.12.1
    3) angular#~1.3.0 which resolved to 1.3.20 and is required by angular-slick#0.2.1
    4) angular#1.3.20 which resolved to 1.3.20 and is required by angular-cookies#1.3.20
    5) angular#~1.3.6 which resolved to 1.3.20 and is required by ng-material-floating-button#0.6.2
    6) angular#~1.3.4 which resolved to 1.3.20 and is required by customerWebapp
    7) angular#~1.4.6 which resolved to 1.4.12 and is required by angular-tour#0.2.5
    8) angular#^1.0.0 which resolved to 1.5.7 and is required by angular-smart-table#2.1.8
    9) angular#>=1.3 which resolved to 1.5.7 and is required by ez-ng#0.1.8
    10) angular#^1.3.x which resolved to 1.5.7 and is required by videogular#1.3.2
    11) angular#>= 1.1.5 which resolved to 1.5.7 and is required by angulartics#0.17.2
    12) angular#^1.2.0 which resolved to 1.5.7 and is required by ngSmoothScroll#2.0.0
    13) angular#>=1.2.10 which resolved to 1.5.7 and is required by angular-carousel#0.3.13
    14) angular#1.5.7 which resolved to 1.5.7 and is required by angular-touch#1.5.7
    15) angular#^1.2.x which resolved to 1.5.7 and is required by angular-update-meta#1.7.1
    16) angular#>=1.0.8 which resolved to 1.5.7 and is required by ngstorage#0.3.10
    17) angular#>=1.4.0 which resolved to 1.5.7 and is required by angular-bootstrap#1.3.3

Prefix the choice with ! to persist it to bower.json

? Answer !6
bower angular                          resolution Saved angular#~1.3.4 as resolution

Unable to find a suitable version for angular-bootstrap, please choose one by typing one of the numbers below:
    1) angular-bootstrap#~0.12.0 which resolved to 0.12.1 and is required by customerWebapp
    2) angular-bootstrap#>=0.14.3 which resolved to 1.3.3 and is required by angular-ui-tour#0.5.4

Prefix the choice with ! to persist it to bower.json

? Answer !1
bower angular-bootstrap                resolution Saved angular-bootstrap#~0.12.0 as resolution

and as soon as i use updated libs our code stops working and when i use our required version it gives below error : 
angular.js:63 Uncaught Error: [$injector:modulerr] Failed to instantiate module customerWebapp due to:
Error: [$injector:modulerr] Failed to instantiate module bm.uiTour due to:
Error: [$injector:unpr] Unknown provider: $uibTooltipProvider
http://errors.angularjs.org/1.3.20/$injector/unpr?p0=%24uibTooltipProvider
    at http://localhost:3000/bower_components/angular/angular.js:63:12
    at http://localhost:3000/bower_components/angular/angular.js:4031:19
    at getService (http://localhost:3000/bower_components/angular/angular.js:4178:39)
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4210:13)
    at runInvokeQueue (http://localhost:3000/bower_components/angular/angular.js:4125:35)
    at http://localhost:3000/bower_components/angular/angular.js:4134:11
    at forEach (http://localhost:3000/bower_components/angular/angular.js:326:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4115:5)
    at http://localhost:3000/bower_components/angular/angular.js:4132:40
    at forEach (http://localhost:3000/bower_components/angular/angular.js:326:20)
http://errors.angularjs.org/1.3.20/$injector/modulerr?p0=bm.uiTour&p1=Error…2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A326%3A20)
    at http://localhost:3000/bower_components/angular/angular.js:63:12
    at http://localhost:3000/bower_components/angular/angular.js:4154:15
    at forEach (http://localhost:3000/bower_components/angular/angular.js:326:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4115:5)
    at http://localhost:3000/bower_components/angular/angular.js:4132:40
    at forEach (http://localhost:3000/bower_components/angular/angular.js:326:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4115:5)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:4041:11)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1455:20)
    at bootstrap (http://localhost:3000/bower_components/angular/angular.js:1476:12)
http://errors.angularjs.org/1.3.20/$injector/modulerr?p0=customerWebapp&p1=…F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A1476%3A12)(anonymous function) @ angular.js:63(anonymous function) @ angular.js:4154forEach @ angular.js:326loadModules @ angular.js:4115createInjector @ angular.js:4041doBootstrap @ angular.js:1455bootstrap @ angular.js:1476angularInit @ angular.js:1370(anonymous function) @ angular.js:26446j @ jquery.min.js:2fireWith @ jquery.min.js:2ready @ jquery.min.js:2J @ jquery.min.js:2
(index):201 GET http://cdn.segment.com/analytics.js/v1/@@segmentKey/analytics.min.js analytics.load @ (index):201(anonymous function) @ (index):204(anonymous function) @ (index):207

I know we should update libraries at our end but if there is any work around

**Comment by aashhissh** [comment]
{
  "name": "customerWebapp",
  "version": "0.0.0",
  "dependencies": {
    "angular": "~1.3.4",
    "angular-bootstrap": "~0.12.0",
    "angular-bootstrap-datetimepicker": "latest",
    "angular-carousel": "~0.3.10",
    "angular-cookies": "~1.3.15",
    "angular-resource": "~1.3.15",
    "angular-route": "~1.3.4",
    "angular-slick": "~0.2.1",
    "angular-smart-table": "~2.1.1",
    "angulartics": "~0.17.2",
    "blueimp-gallery": "~2.15.2",
    "bootstrap-sass-official": "~3.3.1",
    "bower-videogular-youtube": "videogular-youtube#~2.0.4",
    "font-awesome": "~4.3.0",
    "lodash": "~3.7.0",
    "moment": "~2.10.2",
    "ngstorage": "~0.3.3",
    "satellizer": "~0.12.5",
    "slick-carousel": "~1.5.8",
    "slideout.js": "https://github.com/mango/slideout.git#master",
    "videogular": "~1.3.2",
    "videogular-controls": "~1.3.2",
    "videogular-overlay-play": "~1.3.2",
    "videogular-poster": "~1.3.2",
    "videogular-themes-default": "~1.3.2",
    "angular-sticky-navigation-directive": "ng-sticky#~0.0.6",
    "angular-update-meta": "~1.7.0",
    "angular-socialshare": "angularjs-socialshare#^2.1.10",
    "ng-material-floating-button": "ng-mfb#^0.6.2",
    "angular-ui-tour": "latest"
  },
  "devDependencies": {
    "angular-mocks": "~1.3.4"
  },
  "resolutions": {
    "angular": "~1.3.4",
    "slick-carousel": "~1.5.8",
    "videogular": "~1.3.2",
    "angular-bootstrap": "~0.12.0"
  }
}

**Comment by benmarch** [comment]
Hey @aashhissh, the strange thing that I see in your first comment is: `1) angular#~1.2.23 which resolved to 1.2.29 and is required by angular-bootstrap-tour#0.3.4` which is the wrong dependency, you want `angular-ui-tour` which appears in your bower manifest. You are also going to need Angular UI Bootstrap >= 0.14.3, that is a must. If your other dependencies or app code does not support that version of AUIB then you will either have to upgrade/refactor or use Angular Bootstrap Tour which doesn't depend on AUIB. 

Closing as this is a dependency issue and not an issue with the library.
