### ISSUE TITLE
Remove dependency on Angular UI Bootstrap

### ISSUE THREAD

**Issue by benmarch** [benmarch/angular-ui-tour#66]
I know that this library was created to use UIB, but they change their tooltip/popover implementation too often for me to keep up. Also, there are known issues with position popovers in certain conditions, particularly on `position: fixed;` elements. I am either going to find a standalone popover library that lets me customize the UI so that it looks like it does currently, or I will create a very simple popover implementation that I can control.

Their latest changes in v2.0.0 are too much for me to create a way to keep this working in both the latest version and legacy versions, see #65.

**Comment by gauravarora** [comment]
Maybe you could just drop support for angular-bootstrap 1.x in v1.0.0? That way you just need to maintain one version.

**Comment by benmarch** [comment]
THIS IS FINALLY DONE! Version 0.8.0!
