### ISSUE TITLE
using the tour with a page that has <form ng-submit="someMethod()"> will call someMethod on onEnd and onPause events

### ISSUE THREAD

**Issue by blairmotchan** [benmarch/angular-ui-tour#7]
removing the ng-submit form the form tag and then using the ng-click="someMethod" elsewhere in my form solved the problem.  However, I wanted to point it to other potential users.

**Comment by benmarch** [comment]
Hi @blairmotchan, I have not been able to reproduce this issue. I tried just adding the following markup to the page and pausing a tour, but onSubmit() was never called:

    <form ng-submit="onSubmit()">
        Test: <input type="text">
    </form>

I can't find anything in the code that would cause onSubmit() to be called unless it is also set as the onPause or onEnd callback. Do you have an example that I can look at?

**Comment by benmarch** [comment]
Hi @blairmotchan, any update on this?

**Comment by blairmotchan** [comment]
Very sorry - I have been too busy and did not get a chance to go back and look into this for you.  This weekend I'll see if I can generalize my code and reproduce the error.  Thank you!

**Comment by benmarch** [comment]
Cool, no problem, thank you!

**Comment by blairmotchan** [comment]
I have not had a chance to come back to this.  I'll just close the issue because you looked into and could not reproduce.  It's not stopping me or blocking me by any means.

Thank you very much for looking into this issue.

**Comment by kameelyan** [comment]
Wanted to point out that I'm experiencing this same issue right now. Still investigating, and I can't put my code out on the web right now, but just wanted to point it out.

**Comment by kameelyan** [comment]
Ok, so it's not firing that event, but what it is firing is my form validation checks. So for some reason it's thinking the form is being submitted.
