### ISSUE TITLE
Handling Conditions before onNext

### ISSUE THREAD

**Issue by rajasaur** [benmarch/angular-ui-tour#70]
I havent tried the library yet, but just looking at the features to make sure it works for our Angular 1.x SPA.

I would like to make sure that the user has filled in certain values (or selected from a dropdown etc) before she can move to the next step. I did not see examples for this, but browsed over the documentation. Is onNext the place to handle this, i.e. check the scope of the main page and see if the model has the required value and if not, reject the promise to keep them in the same step till they have entered the required value.

Thanks!

**Comment by benmarch** [comment]
Hi @rajasaur, sorry for the delayed response. I haven't tried to do anything like that, nor have I seen it set up that way by another developer, but it sounds very reasonable to me. I will try to add it to the demo.

**Comment by ddemid** [comment]
Hi @benmarch,

Any luck with this? It sounds like a nice to have feature.

**Comment by skalamichal** [comment]
Hi, maybe this could be useful. You can always add variables to the tour instance, which you can update on runtime and which are also available within the popup template. When the tour is executed for the first time, you can set it to false:
```
var tour = uiTourService.getTour();
tour.continueToNext = false;
tour.start();
```
Then you can update the templateUrl, where the tour is added to the scope, so you can enable/disable the next button based on the `tour.continueToNext` value. This is example template, similar to the one I'm using:
```
<div>
	<div class="row">
		<div class="col-xs-12" style="margin-bottom: 10px" ng-bind-html="tourStep.trustedContent"></div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<div class="pull-left">
				<button class="btn btn-sm btn-default" data-role="end" ng-click="tour.customEnd()">End tour</button>
			</div>

			<div class="btn-group pull-right">
				<button class="btn btn-sm btn-default" ng-if="tourStep.isPrev()" ng-click="tour.prev()">
					<i class="fa fa-fw fa-caret-left"></i> Prev
				</button>
				<button class="btn btn-sm btn-primary" ng-if="tourStep.isNext() && tour.continueToNext" ng-click="tour.next()">
					Next <i class="fa fa-fw fa-caret-right"></i>
				</button>
			</div>
		</div>
	</div>
</div>
```
Then in your page controller you can set this value to "true":
```
// any code
if (anyCondition) {
   var tour = uiTourService.getTour();
   tour.continueToNext = true;
}
```
In the Angular application config block set the template to the one you'd like to use, example:
```
.config(function (TourConfigProvider) {
	TourConfigProvider.set('templateUrl', 'templates/modules/walkthrough/tour-popup-intro.html');
})
```
Hope this helps you,
Michal
