### ISSUE TITLE
Angular-Ui-Tour Module Failing to Load into Application

### ISSUE THREAD

**Issue by nicolairobles** [benmarch/angular-ui-tour#74]
**I am using the _exact_ versions of the following libraries:**

* AngularJS: 1.4.7
* Angular Bootstrap: 0.12.1
* Angular UI Tour: file doesn't state

**I have installed this library via:** NPM

**I have observed the following behavior:**
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module bm.uiTour due to:
Error: [$injector:unpr] Unknown provider: $uibTooltipProvider

**This is how I expected it to behave:**
To load my page

**Additional notes/code:**
I'm not able to load bm.uiTour as a module into my app. I've added the module into my config file, I've added the correct files in the HTML. The angular-ui-tour.js is not being read for some reason.

**Comment by benmarch** [comment]
Hey @nicolairobles, if you are using UI Tour 0.6.x then you have to bump up to Angular Bootstrap 2.x. If you are using UI Tour 0.5.x then you need Angular Bootstrap 1.x. Older versions of UI Tour support Angular Bootstrap 0.12.1, but support has been dropped. Check the package.json file under node_modules/angular-ui-tour to see the version.
