### ISSUE TITLE
Popover Animation not working

### ISSUE THREAD

**Issue by houston88** [benmarch/angular-ui-tour#75]
AngularJS: 1.5
Angular Bootstrap: 1.3.2
Angular UI Tour: 0.6.1
Installed via bower.

**I have observed the following behavior:**
Popovers do not animate or fade in or out, even when specifying animation true.

**This is how I expected it to behave:**
I was expecting fade in and out similar to ui bootstrap popovers that specify popover-animation="true"

**Here is my tour config, and all related step configs:**

js:
TourConfigProvider.set('animation',true);

html:
<span tour-step tour-step-scroll-into-view="false" tour-step-title="Recent Activity" tour-step-content="All of your client's recent activity is shown here. From accepting invitations to answering your requests, all at a glance." tour-step-order="30" tour-step-placement="left">
            Hello There
</span>

Notes:
It looks like the proper attributes are not getting set. Perhaps set popover-animation="true" if animation is set to true? Right now I only see animation="animation" on the ui-tour popover. Or add .fade .in classes?

**Comment by benmarch** [comment]
Hey @houston88, UI Tour 0.6.1 is not compatible with Angular Bootstrap 1.3.2, which might be the cause of the behavior that you have observed. Try upgrading Angular Bootstrap to 2.x, or downgrading UI Tour to 0.5.x. Please let me know if that helps.

**Comment by houston88** [comment]
Yup, that was it. I upgraded and the fade in/out is working. Now just trying to see if upgrading angular-bootstrap broke anything else in my app... did not notice anything right off the bat. Thanks!

**Comment by benmarch** [comment]
Awesome! Sorry for the inconvenience, i didn't intend on dropping support for Angular Bootstrap 1.x but they made very significant changes that i couldn't shim easily.

**Comment by houston88** [comment]
Oh yeah, forgot to mention earlier, you may want to update readme, it says something like IMPORTANT: Does not work with Angular Bootstrap 2.0.0 or later.

**Comment by benmarch** [comment]
Good call, I'll update it this weekend, thanks!
