### ISSUE TITLE
Tour always skips second step

### ISSUE THREAD

**Issue by solidevolution** [benmarch/angular-ui-tour#77]
**I am using the _exact_ versions of the following libraries:**
- AngularJS: 1.4.8
- Angular Bootstrap: 1.1.0 (2016-01-18)
- Angular UI Tour: 0.5.0 or 0.6.1

**I have installed this library manually from dist folders, build with gulp

**I have observed the following behavior:**

I created 3 steps, first step appears, after I click on next, third step appears. ui-tour completely ignores the second step.

**This is how I expected it to behave:**

step 1 > next > step 2 > next > step 3

**Here is my tour config, and all related step configs:**

``` html
<body [...] ui-tour ui-tour-on-prev="onPrev(tour)" ui-tour-use-hotkeys="true" ui-tour-append-to-body="true">[...]</div>
```

``` html
        <div 
            tour-step
            tour-step-title="Courses"
            tour-step-content="Text 1"
            tour-step-order="10"
            tour-step-orphan="true"
            tour-step-backdrop="true">
        </div>
        <div 
            tour-step
            tour-step-title="Map"
            tour-step-content="Text 2"
            tour-step-order="20"
            tour-step-orphan="true"
            tour-step-backdrop="true">
        </div>
        <div 
            tour-step
            tour-step-title="Filter"
            tour-step-content="Text 3"
            tour-step-order="30"
            tour-step-orphan="true"
            tour-step-backdrop="true">
        </div>
```

**Additional notes/code:**

Tried it with or without tour-step value, tour-step-orphan, tour-step-backdrop, tour-step-order and all possibilities with or without the body options. It always goes from step 1 to step 3 ...

**Comment by benmarch** [comment]
There was an issue like this way back in version 0.3.x that got resolved, I wonder if I reintroduced it somehow. Can you try installing UI Tour 0.5.5 to see if that works? That was the most recent release that supports your version of Angular Bootstrap.

**Comment by solidevolution** [comment]
Gave it a try, same with 0.5.5 ...

Maybe this list of integrated vendor modules will help you find the issue

```
            'ngRaven',
            'ngCookies',
            'ngSanitize',
            'pascalprecht.translate',
            'tmh.dynamicLocale',
            'ui.router',
            'angular-cache',
            'angular-jwt',
            'angularMoment',
            'angular.filter',
            'angular-clipboard',
            'angular-google-analytics',
            'ui.bootstrap',
            'ui.bootstrap-slider',
            'ngAnimate',
            'angular-loading-bar',
            'angular-ladda',
            'ngFileSaver',
            'ngDialog',
            'ui.select',
            'ngMap',
            'ngGeolocation',
            'ngAutocomplete',
            'bw.paging',
            'bm.uiTour'
```

We also use gulp-template-cache to create the templates in js

**Comment by solidevolution** [comment]
Any news here?

**Comment by benmarch** [comment]
Hey @solidevolution, sorry for the delay. I haven't been able to reproduce the issue at all. Is there any way I can take a look at your app so I can try to debug?

**Comment by solidevolution** [comment]
Not really, it's a customer project

**Comment by benmarch** [comment]
Is the second step wrapped in a ngIf or other directive that could remove the tourStep from the DOM?

**Comment by solidevolution** [comment]
No as you can see in the code above

**Comment by benmarch** [comment]
Hey @solidevolution, please try with the latest version 0.8.0. Note that there are a few breaking changes that might need to be addressed: https://github.com/benmarch/angular-ui-tour#versions.

**Comment by benmarch** [comment]
Hey @solidevolution, any updates?

**Comment by solidevolution** [comment]
Sorry current not on the project. Leaving angular a.t.m.
