### ISSUE TITLE
Allow configuration of a tour-step through a configuration object

### ISSUE THREAD

**Issue by eahousman** [benmarch/angular-ui-tour#81]
It would be nice to have my config set up in my controller:

```
ctrl.tourConfig = {
   title: 'Hello world', 
   content: 'We're doing it!',
   order: 123,
   placement: 'top'
};
```

And implement the tour step using that config:

`<span tour-step tour-step-config="$ctrl.tourConfig"></span>`

Thoughts?

**Comment by benmarch** [comment]
Hey @eahousman, I had this feature originally but it started muddying up some of the more complex configurations so I removed it. I'll consider adding it back one way or another.

**Comment by benmarch** [comment]
Version 0.8.0 has been released, please verify that this issue has been resolved. Note that there are a few breaking changes that might need to be addressed: https://github.com/benmarch/angular-ui-tour#versions.

There is now a `createStep()` method on tours. See README for details.
