### ISSUE TITLE
TourHelpers.safeApply should use root scope to check digest cycle

### ISSUE THREAD

**Issue by ddemid** [benmarch/angular-ui-tour#82]
* AngularJS: 1.4.11
* Angular Bootstrap: 2.1.4
* Angular UI Tour: 0.6.1

**I have installed this library via:** Bower

**I have observed the following behavior:**

Event callbacks aren't working inside directives with isolated scope because of the wrong detection of current digest life cycle.

**Comment by benmarch** [comment]
Released version 0.6.2 with your changes. Let me know if everything is good.

**Comment by ddemid** [comment]
Thank you
