### ISSUE TITLE
Issues with templateUrl and step navigation on detached tour

### ISSUE THREAD

**Issue by PimVV** [benmarch/angular-ui-tour#90]
**I am using the _exact_ versions of the following libraries:**
- AngularJS: 1.5.7
- Bootstrap: 3.3.6
- Angular Bootstrap: 2.0.0
- Angular UI Tour: 0.6.2

**I have installed this library via: Bower** 

**I have observed the following behavior:**
- When I assign a custom templateUrl to the tour config, the tour step only shows the title of the step. The content and navigation are not shown.  I've started from the Bootstrap Tour default HTML in my template. I noticed this template is being injected into the popover-content container, I'm not sure if this is supposed to happen.
- When I leave the templateUrl-option out of the tour config, I see the content en navigation in the tour steps.
  I can click on the 'next' button in the first step and it will show the second step. When I click buttons of the second step (next, prev, end), I get the following error message.

```
angular.js:13920 TypeError: Cannot read property 'config' of null
    at self.goTo (angular-ui-tour.js:745)
    at self.next (angular-ui-tour.js:705)
    ...
```

_**Note:** All the steps are attached to the tour, see notes below for more information._

**This is how I expected it to behave:**
- I expected the templateUrl config option to use my html file (by replacing the default popover), and showing me the content and navigation buttons. 
- I expected the navigation buttons (next, prev, end, ...) not to drop an error but navigate to the next/prev step.

**Here is my tour config, and all related step configs:**

``` js
var general = uiTourService.createDetachedTour('general', {
   name: 'general',
   debug: true,
   useHotkeys: true,
   templateUrl: 'app/components/tour/tour-step.html'
});
```

``` html
<div ui-tour>
   <div tour-step tour-step-belongs-to="general"
        tour-step-title="step 1"
        tour-step-content="this is step 1"
        tour-step-order="10">
   </div>
   <div tour-step tour-step-belongs-to="general"
        tour-step-title="step 2"
        tour-step-content="this is step 2"
        tour-step-order="20">
   </div>
   <div tour-step tour-step-belongs-to="general"
        tour-step-title="step 3"
        tour-step-content="this is step 3"
        tour-step-order="30">
   </div>
</div>
```

``` html
<!-- app/components/tour/tour-step.html -->
<div class='popover tour'>
  <div class='arrow'></div>
  <h3 class='popover-title'></h3>
  <div class='popover-content'></div>
  <div class='popover-navigation'>
    <button class='btn btn-default' data-role='prev'>« Prev</button>
    <span data-role='separator'>|</span>
    <button class='btn btn-default' data-role='next'>Next »</button>
    <button class='btn btn-default' data-role='end'>End tour</button>
  </div>
</div>
```

**Additional notes/code: Troubleshooting**

_**Note:** When checking the tour object and calling the getSteps and getCurrentStep functions, no result is show_

``` js
console.log(general._getSteps()); // []
console.log(general.getCurrentStep()); // null
```

_**Note:** When enabling the useHotkeys option, I can navigate through the entire tour using my keyboard. So all the steps are attached to the tour successfully._

_**Note:** When I automate the tour as below, in order to test the next function, everything works fine and all steps have been completed._

``` js
setTimeout(function(){
   general.next();
},2000);
setTimeout(function(){
   general.next();
},4000);
setTimeout(function(){
   general.end();
},6000);
```

**Comment by PimVV** [comment]
I've noticed the templateUrl issue is resolved using the [angular-ui-tour step template](https://github.com/benmarch/angular-ui-tour/blob/master/app/templates/tour-step-template.html)

Still I am wondering, is only the content replaceable or is there a way to replace the entire popover?

```html
<div>
    <div class="popover-content tour-step-content" ng-bind-html="tourStep.trustedContent"></div>
    <div class="popover-navigation tour-step-navigation">
        <div class="btn-group">
            <button class="btn btn-sm btn-default" ng-if="tourStep.isPrev()" ng-click="tour.prev()">&laquo; Prev</button>
            <button class="btn btn-sm btn-default" ng-if="tourStep.isNext()" ng-click="tour.next()">Next &raquo;</button>
            <button class="btn btn-sm btn-default" data-role="pause-resume" data-pause-text="Pause"
                    data-resume-text="Resume" ng-click="tour.pause()">Pause
            </button>
        </div>
        <button class="btn btn-sm btn-default" data-role="end" ng-click="tour.end()">End tour</button>
    </div>
</div>
```

**Comment by benmarch** [comment]
Hey @PimVV, unfortunately you won't be able to replace the entire template because Angular Bootstrap needs it to properly display the popovers. 

@skalamichal also just found a bug with detached tours that might be affecting you (see #68). Hopefully we will get that patched up quickly.

**Comment by PimVV** [comment]
Hi @benmarch 

The @skalamichal fix did the trick, thanks 👍 I'm looking forward to see this one patched up!
Issue can be closed, let me know when the patch is live!

**Comment by benmarch** [comment]
Hey @PimVV sorry I didn't mention it earlier. This is all set in the latest release. Thanks!
