### ISSUE TITLE
Tour stops or pauses out nextPath

### ISSUE THREAD

**Issue by PimVV** [benmarch/angular-ui-tour#92]
**I am using the _exact_ versions of the following libraries:**

* AngularJS: 1.5.7
* Angular UI Router: 0.3.1
* Angular Bootstrap: 2.0.0
* Angular UI Tour: 0.6.3

I have installed this library via: Bower 

**I have observed the following behavior:**

When I add the nextPath attribute to a step, the redirect works fine using the Angular UI Router but the next step isn't shown. I assume the tour is paused or ended after the redirect.

**This is how I expected it to behave:**

I expected the tour to not to be interrupted by the redirect.

**Here is my tour config, and all related step configs:**

```js
var general = uiTourService.createDetachedTour('general', {
   name: 'general',
   debug: true,
   useHotkeys: true,
   useUiRouter: true,
   templateUrl: 'app/components/tour/tour-step.html'
});
```

```html
<div ui-tour>
   <div tour-step tour-step-belongs-to="general"
        tour-step-title="step 1"
        tour-step-content="this is step 1"
        tour-step-order="10">
   </div>
   <div tour-step tour-step-belongs-to="general"
        tour-step-title="step 2"
        tour-step-content="this is step 2"
        tour-step-order="20"
        tour-step-next-path="index.home">
   </div>
   <div tour-step tour-step-belongs-to="general"
        tour-step-title="step 3"
        tour-step-content="this is step 3"
        tour-step-order="30">
   </div>
</div>
```

**Comment by benmarch** [comment]
Hey @PimVV, you will need to add a couple more attributes to get it working...

To all 3 steps, add a step ID by giving a value to the `tour-step` attribute: `<div tour-step="uniqueId"...`

To step 2, add a `tour-step-next-step="step3Id"` attribute.

To step 3, add `tour-step-prev-path="previous.path" tour-step-prev-step="step2Id"`.

That should do it. Let me know what happens.

**Comment by PimVV** [comment]
I've tried to apply these changes but it didn't seem to work. I've also tested this issue in an isolated testpage with the same result. Switching between step 2 and 3 ends the tour.

I have two other concerns about the extra attributes:

- What if the step before the redirect could occur on several possible pages, is it meaningful to set a prev-path on the next step? 
- Is it necessary to bind next and previous steps, since this is conflicting with the tour step order best practice in a way.

Here's my isolated test case:

```html
<button tour-step="step1"
      tour-step-belongs-to="test"
      tour-step-title="Test tour"
      tour-step-content="This is step 1"
      tour-step-order="10"
      ng-click="TestCtrl.startTestTour(0)">
   step 1
</button>
<button tour-step="step2"
      tour-step-belongs-to="test"
      tour-step-title="Test tour"
      tour-step-content="This is step 2"
      tour-step-order="20"
      tour-step-next-path="index.test"
      tour-step-next-step="step3"
      ng-click="TestCtrl.startTestTour(1)">
   step 2
</button>
<button tour-step="step3"
      tour-step-belongs-to="test"
      tour-step-title="Test tour"
      tour-step-content="This is step 3"
      tour-step-order="30"
      tour-step-prev-path="index.test"
      tour-step-prev-step="step2"
      ng-click="TestCtrl.startTestTour(2)">
   step 3
</button>
<button tour-step="step4"
      tour-step-belongs-to="test"
      tour-step-title="Test tour"
      tour-step-content="This is step 4"
      tour-step-order="40"
      ng-click="TestCtrl.startTestTour(3)">
   step 4
</button>
```

**Comment by benmarch** [comment]
It looks like with your static page that the steps are all in the same view (since the paths are both "index.test") which won't work because it waits for the next/prev step to be added after the redirect. I'm not sure what would prevent this from working if the steps are on different views. Can you paste the exact step declarations here and indicate which view each is in?

It is not necessary to set a prev-step or bind next and prev steps, but the tour will not be able to go back without that set (since it doesn't know about steps not currently in the DOM).

**Comment by PimVV** [comment]
Hey @benmarch, the problem was indeed the redirect only works when I'm on a different page.
I've moved the first step to the home page and started the test tour on the test page and everything worked as it should.

So I can conclude: 

**For the redirect functionality to work, its necessary the next path is a different page that the current page. I assumed this was optional.**

Thanks for your help!

Note: Maybe I'll illustrate the context why ran into this issue in the first place:

> I've build a help feature within the main navigation of my application. From this help feature, a user is able to start a guided tour of choice. The first step of a tour is an orphan step I use as an intro to a tour with a call to action to 'start this tour' (which will move to the next step). 
> 
> Since the help feature can be accessed on any page, I use the redirect to assure the tour is continued on the right page.
> 
> Of course, its always possible the user is already on this page (and in a way, thats likely to happen). So this is where this issue popped up: the intro orphan step was shown but it was not possible to move to the second step.
> 

I'm going to find a workaround for this case.
