### ISSUE TITLE
ez-ng + joint.js bug

### ISSUE THREAD

**Issue by GeorgiyZhuravlev** [benmarch/angular-ui-tour#93]
**I am using the _exact_ versions of the following libraries:**

* AngularJS: 1.4.7
* Angular Bootstrap: 2.2.x
* Angular UI Tour: last

**I have installed this library via:** Bower

**I have observed the following behavior:**

One of the libraries - ez-ng, you're using for angular-ui-tour have a conflict with joint.js (rapid.js) library - http://jointjs.com/
Being only included as a file (not injected) it prevents some diagram parts from drawing (appending to dom).

e.g.
before `bower_components/ez-ng/dist/ez-ng.js` was included
![image](https://cloud.githubusercontent.com/assets/14068189/20006304/99592022-a29f-11e6-9c83-79005ede0b51.png)

after 
![image](https://cloud.githubusercontent.com/assets/14068189/20006351/c6553c46-a29f-11e6-92f4-f0e6c07afcdc.png)

I'm not sure whose fault is this, just want you to be noticed.
someting inside `ezEventEmitter` factory

**Comment by benmarch** [comment]
I have no idea what would cause that. Are there any errors?

**Comment by GeorgiyZhuravlev** [comment]
@benmarch no, no errors shown in the console. 
I'm trying to locate exact part of the code, which produces this bug, but without success yet...

**Comment by benmarch** [comment]
Thanks, @GeorgiyZhuravlev. Please let me know if you find anything, I will be more than happy to fix it on my end if I can.

**Comment by benmarch** [comment]
Any luck with this, @GeorgiyZhuravlev?

**Comment by GeorgiyZhuravlev** [comment]
It was all about `<foreignObject>` in svg generated with joint.js. It appends for some elements html with the own `<body>` tag, so any library/component wich is using "append to body" logic (searching the DOM tree for the `<body>` tag) fail with joint.js... 

Thanks anyway, your component is great! I had to write my own custom solution (derivative from uib-popover) to get the job done, but it is times worse than your component...

**Comment by benmarch** [comment]
Ahh that's really interesting! I think I see why ez-ng is hiding them then: ez-ng uses a library for shimming scoped stylesheets that adds a rule to [hide anything with a body tag](https://github.com/benmarch/ez-ng/blob/100a467fa0c1ab2bcc62ad24c8b262a40234d57b/src/lib/style-scoped-shim.js#L16) while it initializes, and then [shows the document body](https://github.com/benmarch/ez-ng/blob/100a467fa0c1ab2bcc62ad24c8b262a40234d57b/src/lib/style-scoped-shim.js#L51) when it's done.

Thank you for solving this one, I will work to fix ez-ng. I'll let you know when it's all set and maybe you can switch back to this.
