### ISSUE TITLE
Look for tour-step-content changes and update the tour popover content

### ISSUE THREAD

**Issue by skalamichal** [benmarch/angular-ui-tour#94]
Hi Ben,

I added an update to the tour-step directive, which looks for the tour-step-content changes and updates the trustedContent property. I needed the update for my app, where the content is changed after the user logs in to display its name in detached tour step. 

I'd like to make pull request, if you find this useful for other people as well.

Please, let me know.
Michal

**Comment by benmarch** [comment]
Hey Michal, sorry for the delay. Yes, if you would like to create a PR that would be awesome. Please note that I made a large change the codebase so you might have to rebase and resolve conflicts. Thanks!

**Comment by benmarch** [comment]
Hey Michal, I am going to close this in favor of #79. Let me know if you are still up for creating a PR. I am going to add this to the 0.7.1 release.

Thanks,
Ben

**Comment by skalamichal** [comment]
Hi Ben,

I'll update the codebase and fix the issue, then I can do the PR - it can take 2-3 days.

Michal

**Comment by skalamichal** [comment]
Managed to update the code today.

Michal
